// Code generated by ent, DO NOT EDIT.

package appconfig

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appconfig type in the database.
	Label = "app_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldDataDir holds the string denoting the data_dir field in the database.
	FieldDataDir = "data_dir"
	// FieldSchedulerHour holds the string denoting the scheduler_hour field in the database.
	FieldSchedulerHour = "scheduler_hour"
	// FieldReminderDays holds the string denoting the reminder_days field in the database.
	FieldReminderDays = "reminder_days"
	// FieldLogLevel holds the string denoting the log_level field in the database.
	FieldLogLevel = "log_level"
	// FieldLogBufferSize holds the string denoting the log_buffer_size field in the database.
	FieldLogBufferSize = "log_buffer_size"
	// FieldOtelEndpoint holds the string denoting the otel_endpoint field in the database.
	FieldOtelEndpoint = "otel_endpoint"
	// FieldBackupDir holds the string denoting the backup_dir field in the database.
	FieldBackupDir = "backup_dir"
	// FieldBackupRetentionDays holds the string denoting the backup_retention_days field in the database.
	FieldBackupRetentionDays = "backup_retention_days"
	// FieldSMTPHost holds the string denoting the smtp_host field in the database.
	FieldSMTPHost = "smtp_host"
	// FieldSMTPPort holds the string denoting the smtp_port field in the database.
	FieldSMTPPort = "smtp_port"
	// FieldSMTPUser holds the string denoting the smtp_user field in the database.
	FieldSMTPUser = "smtp_user"
	// FieldSMTPPass holds the string denoting the smtp_pass field in the database.
	FieldSMTPPass = "smtp_pass"
	// FieldSMTPTLS holds the string denoting the smtp_tls field in the database.
	FieldSMTPTLS = "smtp_tls"
	// FieldSMTPTimeout holds the string denoting the smtp_timeout field in the database.
	FieldSMTPTimeout = "smtp_timeout"
	// FieldNotifyEmail holds the string denoting the notify_email field in the database.
	FieldNotifyEmail = "notify_email"
	// FieldGotifyURL holds the string denoting the gotify_url field in the database.
	FieldGotifyURL = "gotify_url"
	// FieldGotifyToken holds the string denoting the gotify_token field in the database.
	FieldGotifyToken = "gotify_token"
	// FieldTelegramBotToken holds the string denoting the telegram_bot_token field in the database.
	FieldTelegramBotToken = "telegram_bot_token"
	// FieldTelegramChatID holds the string denoting the telegram_chat_id field in the database.
	FieldTelegramChatID = "telegram_chat_id"
	// FieldUmamiURL holds the string denoting the umami_url field in the database.
	FieldUmamiURL = "umami_url"
	// FieldUmamiWebsiteID holds the string denoting the umami_website_id field in the database.
	FieldUmamiWebsiteID = "umami_website_id"
	// FieldEinkMode holds the string denoting the eink_mode field in the database.
	FieldEinkMode = "eink_mode"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the appconfig in the database.
	Table = "app_configs"
)

// Columns holds all SQL columns for appconfig fields.
var Columns = []string{
	FieldID,
	FieldPort,
	FieldDataDir,
	FieldSchedulerHour,
	FieldReminderDays,
	FieldLogLevel,
	FieldLogBufferSize,
	FieldOtelEndpoint,
	FieldBackupDir,
	FieldBackupRetentionDays,
	FieldSMTPHost,
	FieldSMTPPort,
	FieldSMTPUser,
	FieldSMTPPass,
	FieldSMTPTLS,
	FieldSMTPTimeout,
	FieldNotifyEmail,
	FieldGotifyURL,
	FieldGotifyToken,
	FieldTelegramBotToken,
	FieldTelegramChatID,
	FieldUmamiURL,
	FieldUmamiWebsiteID,
	FieldEinkMode,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AppConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByDataDir orders the results by the data_dir field.
func ByDataDir(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataDir, opts...).ToFunc()
}

// BySchedulerHour orders the results by the scheduler_hour field.
func BySchedulerHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchedulerHour, opts...).ToFunc()
}

// ByReminderDays orders the results by the reminder_days field.
func ByReminderDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReminderDays, opts...).ToFunc()
}

// ByLogLevel orders the results by the log_level field.
func ByLogLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogLevel, opts...).ToFunc()
}

// ByLogBufferSize orders the results by the log_buffer_size field.
func ByLogBufferSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogBufferSize, opts...).ToFunc()
}

// ByOtelEndpoint orders the results by the otel_endpoint field.
func ByOtelEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOtelEndpoint, opts...).ToFunc()
}

// ByBackupDir orders the results by the backup_dir field.
func ByBackupDir(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupDir, opts...).ToFunc()
}

// ByBackupRetentionDays orders the results by the backup_retention_days field.
func ByBackupRetentionDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupRetentionDays, opts...).ToFunc()
}

// BySMTPHost orders the results by the smtp_host field.
func BySMTPHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPHost, opts...).ToFunc()
}

// BySMTPPort orders the results by the smtp_port field.
func BySMTPPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPPort, opts...).ToFunc()
}

// BySMTPUser orders the results by the smtp_user field.
func BySMTPUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPUser, opts...).ToFunc()
}

// BySMTPPass orders the results by the smtp_pass field.
func BySMTPPass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPPass, opts...).ToFunc()
}

// BySMTPTLS orders the results by the smtp_tls field.
func BySMTPTLS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPTLS, opts...).ToFunc()
}

// BySMTPTimeout orders the results by the smtp_timeout field.
func BySMTPTimeout(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPTimeout, opts...).ToFunc()
}

// ByNotifyEmail orders the results by the notify_email field.
func ByNotifyEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyEmail, opts...).ToFunc()
}

// ByGotifyURL orders the results by the gotify_url field.
func ByGotifyURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGotifyURL, opts...).ToFunc()
}

// ByGotifyToken orders the results by the gotify_token field.
func ByGotifyToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGotifyToken, opts...).ToFunc()
}

// ByTelegramBotToken orders the results by the telegram_bot_token field.
func ByTelegramBotToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelegramBotToken, opts...).ToFunc()
}

// ByTelegramChatID orders the results by the telegram_chat_id field.
func ByTelegramChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelegramChatID, opts...).ToFunc()
}

// ByUmamiURL orders the results by the umami_url field.
func ByUmamiURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUmamiURL, opts...).ToFunc()
}

// ByUmamiWebsiteID orders the results by the umami_website_id field.
func ByUmamiWebsiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUmamiWebsiteID, opts...).ToFunc()
}

// ByEinkMode orders the results by the eink_mode field.
func ByEinkMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEinkMode, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
