// Code generated by ent, DO NOT EDIT.

package appconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/datey/datey/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldID, id))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldPort, v))
}

// DataDir applies equality check predicate on the "data_dir" field. It's identical to DataDirEQ.
func DataDir(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldDataDir, v))
}

// SchedulerHour applies equality check predicate on the "scheduler_hour" field. It's identical to SchedulerHourEQ.
func SchedulerHour(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSchedulerHour, v))
}

// ReminderDays applies equality check predicate on the "reminder_days" field. It's identical to ReminderDaysEQ.
func ReminderDays(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldReminderDays, v))
}

// LogLevel applies equality check predicate on the "log_level" field. It's identical to LogLevelEQ.
func LogLevel(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldLogLevel, v))
}

// LogBufferSize applies equality check predicate on the "log_buffer_size" field. It's identical to LogBufferSizeEQ.
func LogBufferSize(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldLogBufferSize, v))
}

// OtelEndpoint applies equality check predicate on the "otel_endpoint" field. It's identical to OtelEndpointEQ.
func OtelEndpoint(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldOtelEndpoint, v))
}

// BackupDir applies equality check predicate on the "backup_dir" field. It's identical to BackupDirEQ.
func BackupDir(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldBackupDir, v))
}

// BackupRetentionDays applies equality check predicate on the "backup_retention_days" field. It's identical to BackupRetentionDaysEQ.
func BackupRetentionDays(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldBackupRetentionDays, v))
}

// SMTPHost applies equality check predicate on the "smtp_host" field. It's identical to SMTPHostEQ.
func SMTPHost(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPHost, v))
}

// SMTPPort applies equality check predicate on the "smtp_port" field. It's identical to SMTPPortEQ.
func SMTPPort(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPPort, v))
}

// SMTPUser applies equality check predicate on the "smtp_user" field. It's identical to SMTPUserEQ.
func SMTPUser(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPUser, v))
}

// SMTPPass applies equality check predicate on the "smtp_pass" field. It's identical to SMTPPassEQ.
func SMTPPass(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPPass, v))
}

// SMTPTLS applies equality check predicate on the "smtp_tls" field. It's identical to SMTPTLSEQ.
func SMTPTLS(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPTLS, v))
}

// SMTPTimeout applies equality check predicate on the "smtp_timeout" field. It's identical to SMTPTimeoutEQ.
func SMTPTimeout(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPTimeout, v))
}

// NotifyEmail applies equality check predicate on the "notify_email" field. It's identical to NotifyEmailEQ.
func NotifyEmail(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldNotifyEmail, v))
}

// GotifyURL applies equality check predicate on the "gotify_url" field. It's identical to GotifyURLEQ.
func GotifyURL(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldGotifyURL, v))
}

// GotifyToken applies equality check predicate on the "gotify_token" field. It's identical to GotifyTokenEQ.
func GotifyToken(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldGotifyToken, v))
}

// TelegramBotToken applies equality check predicate on the "telegram_bot_token" field. It's identical to TelegramBotTokenEQ.
func TelegramBotToken(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldTelegramBotToken, v))
}

// TelegramChatID applies equality check predicate on the "telegram_chat_id" field. It's identical to TelegramChatIDEQ.
func TelegramChatID(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldTelegramChatID, v))
}

// UmamiURL applies equality check predicate on the "umami_url" field. It's identical to UmamiURLEQ.
func UmamiURL(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldUmamiURL, v))
}

// UmamiWebsiteID applies equality check predicate on the "umami_website_id" field. It's identical to UmamiWebsiteIDEQ.
func UmamiWebsiteID(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldUmamiWebsiteID, v))
}

// EinkMode applies equality check predicate on the "eink_mode" field. It's identical to EinkModeEQ.
func EinkMode(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldEinkMode, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldPort, v))
}

// PortIsNil applies the IsNil predicate on the "port" field.
func PortIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldPort))
}

// PortNotNil applies the NotNil predicate on the "port" field.
func PortNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldPort))
}

// DataDirEQ applies the EQ predicate on the "data_dir" field.
func DataDirEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldDataDir, v))
}

// DataDirNEQ applies the NEQ predicate on the "data_dir" field.
func DataDirNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldDataDir, v))
}

// DataDirIn applies the In predicate on the "data_dir" field.
func DataDirIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldDataDir, vs...))
}

// DataDirNotIn applies the NotIn predicate on the "data_dir" field.
func DataDirNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldDataDir, vs...))
}

// DataDirGT applies the GT predicate on the "data_dir" field.
func DataDirGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldDataDir, v))
}

// DataDirGTE applies the GTE predicate on the "data_dir" field.
func DataDirGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldDataDir, v))
}

// DataDirLT applies the LT predicate on the "data_dir" field.
func DataDirLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldDataDir, v))
}

// DataDirLTE applies the LTE predicate on the "data_dir" field.
func DataDirLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldDataDir, v))
}

// DataDirContains applies the Contains predicate on the "data_dir" field.
func DataDirContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldDataDir, v))
}

// DataDirHasPrefix applies the HasPrefix predicate on the "data_dir" field.
func DataDirHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldDataDir, v))
}

// DataDirHasSuffix applies the HasSuffix predicate on the "data_dir" field.
func DataDirHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldDataDir, v))
}

// DataDirIsNil applies the IsNil predicate on the "data_dir" field.
func DataDirIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldDataDir))
}

// DataDirNotNil applies the NotNil predicate on the "data_dir" field.
func DataDirNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldDataDir))
}

// DataDirEqualFold applies the EqualFold predicate on the "data_dir" field.
func DataDirEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldDataDir, v))
}

// DataDirContainsFold applies the ContainsFold predicate on the "data_dir" field.
func DataDirContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldDataDir, v))
}

// SchedulerHourEQ applies the EQ predicate on the "scheduler_hour" field.
func SchedulerHourEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSchedulerHour, v))
}

// SchedulerHourNEQ applies the NEQ predicate on the "scheduler_hour" field.
func SchedulerHourNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldSchedulerHour, v))
}

// SchedulerHourIn applies the In predicate on the "scheduler_hour" field.
func SchedulerHourIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldSchedulerHour, vs...))
}

// SchedulerHourNotIn applies the NotIn predicate on the "scheduler_hour" field.
func SchedulerHourNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldSchedulerHour, vs...))
}

// SchedulerHourGT applies the GT predicate on the "scheduler_hour" field.
func SchedulerHourGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldSchedulerHour, v))
}

// SchedulerHourGTE applies the GTE predicate on the "scheduler_hour" field.
func SchedulerHourGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldSchedulerHour, v))
}

// SchedulerHourLT applies the LT predicate on the "scheduler_hour" field.
func SchedulerHourLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldSchedulerHour, v))
}

// SchedulerHourLTE applies the LTE predicate on the "scheduler_hour" field.
func SchedulerHourLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldSchedulerHour, v))
}

// SchedulerHourIsNil applies the IsNil predicate on the "scheduler_hour" field.
func SchedulerHourIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldSchedulerHour))
}

// SchedulerHourNotNil applies the NotNil predicate on the "scheduler_hour" field.
func SchedulerHourNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldSchedulerHour))
}

// ReminderDaysEQ applies the EQ predicate on the "reminder_days" field.
func ReminderDaysEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldReminderDays, v))
}

// ReminderDaysNEQ applies the NEQ predicate on the "reminder_days" field.
func ReminderDaysNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldReminderDays, v))
}

// ReminderDaysIn applies the In predicate on the "reminder_days" field.
func ReminderDaysIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldReminderDays, vs...))
}

// ReminderDaysNotIn applies the NotIn predicate on the "reminder_days" field.
func ReminderDaysNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldReminderDays, vs...))
}

// ReminderDaysGT applies the GT predicate on the "reminder_days" field.
func ReminderDaysGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldReminderDays, v))
}

// ReminderDaysGTE applies the GTE predicate on the "reminder_days" field.
func ReminderDaysGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldReminderDays, v))
}

// ReminderDaysLT applies the LT predicate on the "reminder_days" field.
func ReminderDaysLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldReminderDays, v))
}

// ReminderDaysLTE applies the LTE predicate on the "reminder_days" field.
func ReminderDaysLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldReminderDays, v))
}

// ReminderDaysIsNil applies the IsNil predicate on the "reminder_days" field.
func ReminderDaysIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldReminderDays))
}

// ReminderDaysNotNil applies the NotNil predicate on the "reminder_days" field.
func ReminderDaysNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldReminderDays))
}

// LogLevelEQ applies the EQ predicate on the "log_level" field.
func LogLevelEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldLogLevel, v))
}

// LogLevelNEQ applies the NEQ predicate on the "log_level" field.
func LogLevelNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldLogLevel, v))
}

// LogLevelIn applies the In predicate on the "log_level" field.
func LogLevelIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldLogLevel, vs...))
}

// LogLevelNotIn applies the NotIn predicate on the "log_level" field.
func LogLevelNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldLogLevel, vs...))
}

// LogLevelGT applies the GT predicate on the "log_level" field.
func LogLevelGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldLogLevel, v))
}

// LogLevelGTE applies the GTE predicate on the "log_level" field.
func LogLevelGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldLogLevel, v))
}

// LogLevelLT applies the LT predicate on the "log_level" field.
func LogLevelLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldLogLevel, v))
}

// LogLevelLTE applies the LTE predicate on the "log_level" field.
func LogLevelLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldLogLevel, v))
}

// LogLevelContains applies the Contains predicate on the "log_level" field.
func LogLevelContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldLogLevel, v))
}

// LogLevelHasPrefix applies the HasPrefix predicate on the "log_level" field.
func LogLevelHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldLogLevel, v))
}

// LogLevelHasSuffix applies the HasSuffix predicate on the "log_level" field.
func LogLevelHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldLogLevel, v))
}

// LogLevelIsNil applies the IsNil predicate on the "log_level" field.
func LogLevelIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldLogLevel))
}

// LogLevelNotNil applies the NotNil predicate on the "log_level" field.
func LogLevelNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldLogLevel))
}

// LogLevelEqualFold applies the EqualFold predicate on the "log_level" field.
func LogLevelEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldLogLevel, v))
}

// LogLevelContainsFold applies the ContainsFold predicate on the "log_level" field.
func LogLevelContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldLogLevel, v))
}

// LogBufferSizeEQ applies the EQ predicate on the "log_buffer_size" field.
func LogBufferSizeEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldLogBufferSize, v))
}

// LogBufferSizeNEQ applies the NEQ predicate on the "log_buffer_size" field.
func LogBufferSizeNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldLogBufferSize, v))
}

// LogBufferSizeIn applies the In predicate on the "log_buffer_size" field.
func LogBufferSizeIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldLogBufferSize, vs...))
}

// LogBufferSizeNotIn applies the NotIn predicate on the "log_buffer_size" field.
func LogBufferSizeNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldLogBufferSize, vs...))
}

// LogBufferSizeGT applies the GT predicate on the "log_buffer_size" field.
func LogBufferSizeGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldLogBufferSize, v))
}

// LogBufferSizeGTE applies the GTE predicate on the "log_buffer_size" field.
func LogBufferSizeGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldLogBufferSize, v))
}

// LogBufferSizeLT applies the LT predicate on the "log_buffer_size" field.
func LogBufferSizeLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldLogBufferSize, v))
}

// LogBufferSizeLTE applies the LTE predicate on the "log_buffer_size" field.
func LogBufferSizeLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldLogBufferSize, v))
}

// LogBufferSizeIsNil applies the IsNil predicate on the "log_buffer_size" field.
func LogBufferSizeIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldLogBufferSize))
}

// LogBufferSizeNotNil applies the NotNil predicate on the "log_buffer_size" field.
func LogBufferSizeNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldLogBufferSize))
}

// OtelEndpointEQ applies the EQ predicate on the "otel_endpoint" field.
func OtelEndpointEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldOtelEndpoint, v))
}

// OtelEndpointNEQ applies the NEQ predicate on the "otel_endpoint" field.
func OtelEndpointNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldOtelEndpoint, v))
}

// OtelEndpointIn applies the In predicate on the "otel_endpoint" field.
func OtelEndpointIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldOtelEndpoint, vs...))
}

// OtelEndpointNotIn applies the NotIn predicate on the "otel_endpoint" field.
func OtelEndpointNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldOtelEndpoint, vs...))
}

// OtelEndpointGT applies the GT predicate on the "otel_endpoint" field.
func OtelEndpointGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldOtelEndpoint, v))
}

// OtelEndpointGTE applies the GTE predicate on the "otel_endpoint" field.
func OtelEndpointGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldOtelEndpoint, v))
}

// OtelEndpointLT applies the LT predicate on the "otel_endpoint" field.
func OtelEndpointLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldOtelEndpoint, v))
}

// OtelEndpointLTE applies the LTE predicate on the "otel_endpoint" field.
func OtelEndpointLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldOtelEndpoint, v))
}

// OtelEndpointContains applies the Contains predicate on the "otel_endpoint" field.
func OtelEndpointContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldOtelEndpoint, v))
}

// OtelEndpointHasPrefix applies the HasPrefix predicate on the "otel_endpoint" field.
func OtelEndpointHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldOtelEndpoint, v))
}

// OtelEndpointHasSuffix applies the HasSuffix predicate on the "otel_endpoint" field.
func OtelEndpointHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldOtelEndpoint, v))
}

// OtelEndpointIsNil applies the IsNil predicate on the "otel_endpoint" field.
func OtelEndpointIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldOtelEndpoint))
}

// OtelEndpointNotNil applies the NotNil predicate on the "otel_endpoint" field.
func OtelEndpointNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldOtelEndpoint))
}

// OtelEndpointEqualFold applies the EqualFold predicate on the "otel_endpoint" field.
func OtelEndpointEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldOtelEndpoint, v))
}

// OtelEndpointContainsFold applies the ContainsFold predicate on the "otel_endpoint" field.
func OtelEndpointContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldOtelEndpoint, v))
}

// BackupDirEQ applies the EQ predicate on the "backup_dir" field.
func BackupDirEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldBackupDir, v))
}

// BackupDirNEQ applies the NEQ predicate on the "backup_dir" field.
func BackupDirNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldBackupDir, v))
}

// BackupDirIn applies the In predicate on the "backup_dir" field.
func BackupDirIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldBackupDir, vs...))
}

// BackupDirNotIn applies the NotIn predicate on the "backup_dir" field.
func BackupDirNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldBackupDir, vs...))
}

// BackupDirGT applies the GT predicate on the "backup_dir" field.
func BackupDirGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldBackupDir, v))
}

// BackupDirGTE applies the GTE predicate on the "backup_dir" field.
func BackupDirGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldBackupDir, v))
}

// BackupDirLT applies the LT predicate on the "backup_dir" field.
func BackupDirLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldBackupDir, v))
}

// BackupDirLTE applies the LTE predicate on the "backup_dir" field.
func BackupDirLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldBackupDir, v))
}

// BackupDirContains applies the Contains predicate on the "backup_dir" field.
func BackupDirContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldBackupDir, v))
}

// BackupDirHasPrefix applies the HasPrefix predicate on the "backup_dir" field.
func BackupDirHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldBackupDir, v))
}

// BackupDirHasSuffix applies the HasSuffix predicate on the "backup_dir" field.
func BackupDirHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldBackupDir, v))
}

// BackupDirIsNil applies the IsNil predicate on the "backup_dir" field.
func BackupDirIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldBackupDir))
}

// BackupDirNotNil applies the NotNil predicate on the "backup_dir" field.
func BackupDirNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldBackupDir))
}

// BackupDirEqualFold applies the EqualFold predicate on the "backup_dir" field.
func BackupDirEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldBackupDir, v))
}

// BackupDirContainsFold applies the ContainsFold predicate on the "backup_dir" field.
func BackupDirContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldBackupDir, v))
}

// BackupRetentionDaysEQ applies the EQ predicate on the "backup_retention_days" field.
func BackupRetentionDaysEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldBackupRetentionDays, v))
}

// BackupRetentionDaysNEQ applies the NEQ predicate on the "backup_retention_days" field.
func BackupRetentionDaysNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldBackupRetentionDays, v))
}

// BackupRetentionDaysIn applies the In predicate on the "backup_retention_days" field.
func BackupRetentionDaysIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldBackupRetentionDays, vs...))
}

// BackupRetentionDaysNotIn applies the NotIn predicate on the "backup_retention_days" field.
func BackupRetentionDaysNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldBackupRetentionDays, vs...))
}

// BackupRetentionDaysGT applies the GT predicate on the "backup_retention_days" field.
func BackupRetentionDaysGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldBackupRetentionDays, v))
}

// BackupRetentionDaysGTE applies the GTE predicate on the "backup_retention_days" field.
func BackupRetentionDaysGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldBackupRetentionDays, v))
}

// BackupRetentionDaysLT applies the LT predicate on the "backup_retention_days" field.
func BackupRetentionDaysLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldBackupRetentionDays, v))
}

// BackupRetentionDaysLTE applies the LTE predicate on the "backup_retention_days" field.
func BackupRetentionDaysLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldBackupRetentionDays, v))
}

// BackupRetentionDaysIsNil applies the IsNil predicate on the "backup_retention_days" field.
func BackupRetentionDaysIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldBackupRetentionDays))
}

// BackupRetentionDaysNotNil applies the NotNil predicate on the "backup_retention_days" field.
func BackupRetentionDaysNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldBackupRetentionDays))
}

// SMTPHostEQ applies the EQ predicate on the "smtp_host" field.
func SMTPHostEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPHost, v))
}

// SMTPHostNEQ applies the NEQ predicate on the "smtp_host" field.
func SMTPHostNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldSMTPHost, v))
}

// SMTPHostIn applies the In predicate on the "smtp_host" field.
func SMTPHostIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldSMTPHost, vs...))
}

// SMTPHostNotIn applies the NotIn predicate on the "smtp_host" field.
func SMTPHostNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldSMTPHost, vs...))
}

// SMTPHostGT applies the GT predicate on the "smtp_host" field.
func SMTPHostGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldSMTPHost, v))
}

// SMTPHostGTE applies the GTE predicate on the "smtp_host" field.
func SMTPHostGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldSMTPHost, v))
}

// SMTPHostLT applies the LT predicate on the "smtp_host" field.
func SMTPHostLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldSMTPHost, v))
}

// SMTPHostLTE applies the LTE predicate on the "smtp_host" field.
func SMTPHostLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldSMTPHost, v))
}

// SMTPHostContains applies the Contains predicate on the "smtp_host" field.
func SMTPHostContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldSMTPHost, v))
}

// SMTPHostHasPrefix applies the HasPrefix predicate on the "smtp_host" field.
func SMTPHostHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldSMTPHost, v))
}

// SMTPHostHasSuffix applies the HasSuffix predicate on the "smtp_host" field.
func SMTPHostHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldSMTPHost, v))
}

// SMTPHostIsNil applies the IsNil predicate on the "smtp_host" field.
func SMTPHostIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldSMTPHost))
}

// SMTPHostNotNil applies the NotNil predicate on the "smtp_host" field.
func SMTPHostNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldSMTPHost))
}

// SMTPHostEqualFold applies the EqualFold predicate on the "smtp_host" field.
func SMTPHostEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldSMTPHost, v))
}

// SMTPHostContainsFold applies the ContainsFold predicate on the "smtp_host" field.
func SMTPHostContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldSMTPHost, v))
}

// SMTPPortEQ applies the EQ predicate on the "smtp_port" field.
func SMTPPortEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPPort, v))
}

// SMTPPortNEQ applies the NEQ predicate on the "smtp_port" field.
func SMTPPortNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldSMTPPort, v))
}

// SMTPPortIn applies the In predicate on the "smtp_port" field.
func SMTPPortIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldSMTPPort, vs...))
}

// SMTPPortNotIn applies the NotIn predicate on the "smtp_port" field.
func SMTPPortNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldSMTPPort, vs...))
}

// SMTPPortGT applies the GT predicate on the "smtp_port" field.
func SMTPPortGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldSMTPPort, v))
}

// SMTPPortGTE applies the GTE predicate on the "smtp_port" field.
func SMTPPortGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldSMTPPort, v))
}

// SMTPPortLT applies the LT predicate on the "smtp_port" field.
func SMTPPortLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldSMTPPort, v))
}

// SMTPPortLTE applies the LTE predicate on the "smtp_port" field.
func SMTPPortLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldSMTPPort, v))
}

// SMTPPortIsNil applies the IsNil predicate on the "smtp_port" field.
func SMTPPortIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldSMTPPort))
}

// SMTPPortNotNil applies the NotNil predicate on the "smtp_port" field.
func SMTPPortNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldSMTPPort))
}

// SMTPUserEQ applies the EQ predicate on the "smtp_user" field.
func SMTPUserEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPUser, v))
}

// SMTPUserNEQ applies the NEQ predicate on the "smtp_user" field.
func SMTPUserNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldSMTPUser, v))
}

// SMTPUserIn applies the In predicate on the "smtp_user" field.
func SMTPUserIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldSMTPUser, vs...))
}

// SMTPUserNotIn applies the NotIn predicate on the "smtp_user" field.
func SMTPUserNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldSMTPUser, vs...))
}

// SMTPUserGT applies the GT predicate on the "smtp_user" field.
func SMTPUserGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldSMTPUser, v))
}

// SMTPUserGTE applies the GTE predicate on the "smtp_user" field.
func SMTPUserGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldSMTPUser, v))
}

// SMTPUserLT applies the LT predicate on the "smtp_user" field.
func SMTPUserLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldSMTPUser, v))
}

// SMTPUserLTE applies the LTE predicate on the "smtp_user" field.
func SMTPUserLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldSMTPUser, v))
}

// SMTPUserContains applies the Contains predicate on the "smtp_user" field.
func SMTPUserContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldSMTPUser, v))
}

// SMTPUserHasPrefix applies the HasPrefix predicate on the "smtp_user" field.
func SMTPUserHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldSMTPUser, v))
}

// SMTPUserHasSuffix applies the HasSuffix predicate on the "smtp_user" field.
func SMTPUserHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldSMTPUser, v))
}

// SMTPUserIsNil applies the IsNil predicate on the "smtp_user" field.
func SMTPUserIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldSMTPUser))
}

// SMTPUserNotNil applies the NotNil predicate on the "smtp_user" field.
func SMTPUserNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldSMTPUser))
}

// SMTPUserEqualFold applies the EqualFold predicate on the "smtp_user" field.
func SMTPUserEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldSMTPUser, v))
}

// SMTPUserContainsFold applies the ContainsFold predicate on the "smtp_user" field.
func SMTPUserContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldSMTPUser, v))
}

// SMTPPassEQ applies the EQ predicate on the "smtp_pass" field.
func SMTPPassEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPPass, v))
}

// SMTPPassNEQ applies the NEQ predicate on the "smtp_pass" field.
func SMTPPassNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldSMTPPass, v))
}

// SMTPPassIn applies the In predicate on the "smtp_pass" field.
func SMTPPassIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldSMTPPass, vs...))
}

// SMTPPassNotIn applies the NotIn predicate on the "smtp_pass" field.
func SMTPPassNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldSMTPPass, vs...))
}

// SMTPPassGT applies the GT predicate on the "smtp_pass" field.
func SMTPPassGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldSMTPPass, v))
}

// SMTPPassGTE applies the GTE predicate on the "smtp_pass" field.
func SMTPPassGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldSMTPPass, v))
}

// SMTPPassLT applies the LT predicate on the "smtp_pass" field.
func SMTPPassLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldSMTPPass, v))
}

// SMTPPassLTE applies the LTE predicate on the "smtp_pass" field.
func SMTPPassLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldSMTPPass, v))
}

// SMTPPassContains applies the Contains predicate on the "smtp_pass" field.
func SMTPPassContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldSMTPPass, v))
}

// SMTPPassHasPrefix applies the HasPrefix predicate on the "smtp_pass" field.
func SMTPPassHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldSMTPPass, v))
}

// SMTPPassHasSuffix applies the HasSuffix predicate on the "smtp_pass" field.
func SMTPPassHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldSMTPPass, v))
}

// SMTPPassIsNil applies the IsNil predicate on the "smtp_pass" field.
func SMTPPassIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldSMTPPass))
}

// SMTPPassNotNil applies the NotNil predicate on the "smtp_pass" field.
func SMTPPassNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldSMTPPass))
}

// SMTPPassEqualFold applies the EqualFold predicate on the "smtp_pass" field.
func SMTPPassEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldSMTPPass, v))
}

// SMTPPassContainsFold applies the ContainsFold predicate on the "smtp_pass" field.
func SMTPPassContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldSMTPPass, v))
}

// SMTPTLSEQ applies the EQ predicate on the "smtp_tls" field.
func SMTPTLSEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPTLS, v))
}

// SMTPTLSNEQ applies the NEQ predicate on the "smtp_tls" field.
func SMTPTLSNEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldSMTPTLS, v))
}

// SMTPTLSIsNil applies the IsNil predicate on the "smtp_tls" field.
func SMTPTLSIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldSMTPTLS))
}

// SMTPTLSNotNil applies the NotNil predicate on the "smtp_tls" field.
func SMTPTLSNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldSMTPTLS))
}

// SMTPTimeoutEQ applies the EQ predicate on the "smtp_timeout" field.
func SMTPTimeoutEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldSMTPTimeout, v))
}

// SMTPTimeoutNEQ applies the NEQ predicate on the "smtp_timeout" field.
func SMTPTimeoutNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldSMTPTimeout, v))
}

// SMTPTimeoutIn applies the In predicate on the "smtp_timeout" field.
func SMTPTimeoutIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldSMTPTimeout, vs...))
}

// SMTPTimeoutNotIn applies the NotIn predicate on the "smtp_timeout" field.
func SMTPTimeoutNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldSMTPTimeout, vs...))
}

// SMTPTimeoutGT applies the GT predicate on the "smtp_timeout" field.
func SMTPTimeoutGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldSMTPTimeout, v))
}

// SMTPTimeoutGTE applies the GTE predicate on the "smtp_timeout" field.
func SMTPTimeoutGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldSMTPTimeout, v))
}

// SMTPTimeoutLT applies the LT predicate on the "smtp_timeout" field.
func SMTPTimeoutLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldSMTPTimeout, v))
}

// SMTPTimeoutLTE applies the LTE predicate on the "smtp_timeout" field.
func SMTPTimeoutLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldSMTPTimeout, v))
}

// SMTPTimeoutIsNil applies the IsNil predicate on the "smtp_timeout" field.
func SMTPTimeoutIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldSMTPTimeout))
}

// SMTPTimeoutNotNil applies the NotNil predicate on the "smtp_timeout" field.
func SMTPTimeoutNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldSMTPTimeout))
}

// NotifyEmailEQ applies the EQ predicate on the "notify_email" field.
func NotifyEmailEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldNotifyEmail, v))
}

// NotifyEmailNEQ applies the NEQ predicate on the "notify_email" field.
func NotifyEmailNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldNotifyEmail, v))
}

// NotifyEmailIn applies the In predicate on the "notify_email" field.
func NotifyEmailIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldNotifyEmail, vs...))
}

// NotifyEmailNotIn applies the NotIn predicate on the "notify_email" field.
func NotifyEmailNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldNotifyEmail, vs...))
}

// NotifyEmailGT applies the GT predicate on the "notify_email" field.
func NotifyEmailGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldNotifyEmail, v))
}

// NotifyEmailGTE applies the GTE predicate on the "notify_email" field.
func NotifyEmailGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldNotifyEmail, v))
}

// NotifyEmailLT applies the LT predicate on the "notify_email" field.
func NotifyEmailLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldNotifyEmail, v))
}

// NotifyEmailLTE applies the LTE predicate on the "notify_email" field.
func NotifyEmailLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldNotifyEmail, v))
}

// NotifyEmailContains applies the Contains predicate on the "notify_email" field.
func NotifyEmailContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldNotifyEmail, v))
}

// NotifyEmailHasPrefix applies the HasPrefix predicate on the "notify_email" field.
func NotifyEmailHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldNotifyEmail, v))
}

// NotifyEmailHasSuffix applies the HasSuffix predicate on the "notify_email" field.
func NotifyEmailHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldNotifyEmail, v))
}

// NotifyEmailIsNil applies the IsNil predicate on the "notify_email" field.
func NotifyEmailIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldNotifyEmail))
}

// NotifyEmailNotNil applies the NotNil predicate on the "notify_email" field.
func NotifyEmailNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldNotifyEmail))
}

// NotifyEmailEqualFold applies the EqualFold predicate on the "notify_email" field.
func NotifyEmailEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldNotifyEmail, v))
}

// NotifyEmailContainsFold applies the ContainsFold predicate on the "notify_email" field.
func NotifyEmailContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldNotifyEmail, v))
}

// GotifyURLEQ applies the EQ predicate on the "gotify_url" field.
func GotifyURLEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldGotifyURL, v))
}

// GotifyURLNEQ applies the NEQ predicate on the "gotify_url" field.
func GotifyURLNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldGotifyURL, v))
}

// GotifyURLIn applies the In predicate on the "gotify_url" field.
func GotifyURLIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldGotifyURL, vs...))
}

// GotifyURLNotIn applies the NotIn predicate on the "gotify_url" field.
func GotifyURLNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldGotifyURL, vs...))
}

// GotifyURLGT applies the GT predicate on the "gotify_url" field.
func GotifyURLGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldGotifyURL, v))
}

// GotifyURLGTE applies the GTE predicate on the "gotify_url" field.
func GotifyURLGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldGotifyURL, v))
}

// GotifyURLLT applies the LT predicate on the "gotify_url" field.
func GotifyURLLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldGotifyURL, v))
}

// GotifyURLLTE applies the LTE predicate on the "gotify_url" field.
func GotifyURLLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldGotifyURL, v))
}

// GotifyURLContains applies the Contains predicate on the "gotify_url" field.
func GotifyURLContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldGotifyURL, v))
}

// GotifyURLHasPrefix applies the HasPrefix predicate on the "gotify_url" field.
func GotifyURLHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldGotifyURL, v))
}

// GotifyURLHasSuffix applies the HasSuffix predicate on the "gotify_url" field.
func GotifyURLHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldGotifyURL, v))
}

// GotifyURLIsNil applies the IsNil predicate on the "gotify_url" field.
func GotifyURLIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldGotifyURL))
}

// GotifyURLNotNil applies the NotNil predicate on the "gotify_url" field.
func GotifyURLNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldGotifyURL))
}

// GotifyURLEqualFold applies the EqualFold predicate on the "gotify_url" field.
func GotifyURLEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldGotifyURL, v))
}

// GotifyURLContainsFold applies the ContainsFold predicate on the "gotify_url" field.
func GotifyURLContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldGotifyURL, v))
}

// GotifyTokenEQ applies the EQ predicate on the "gotify_token" field.
func GotifyTokenEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldGotifyToken, v))
}

// GotifyTokenNEQ applies the NEQ predicate on the "gotify_token" field.
func GotifyTokenNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldGotifyToken, v))
}

// GotifyTokenIn applies the In predicate on the "gotify_token" field.
func GotifyTokenIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldGotifyToken, vs...))
}

// GotifyTokenNotIn applies the NotIn predicate on the "gotify_token" field.
func GotifyTokenNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldGotifyToken, vs...))
}

// GotifyTokenGT applies the GT predicate on the "gotify_token" field.
func GotifyTokenGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldGotifyToken, v))
}

// GotifyTokenGTE applies the GTE predicate on the "gotify_token" field.
func GotifyTokenGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldGotifyToken, v))
}

// GotifyTokenLT applies the LT predicate on the "gotify_token" field.
func GotifyTokenLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldGotifyToken, v))
}

// GotifyTokenLTE applies the LTE predicate on the "gotify_token" field.
func GotifyTokenLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldGotifyToken, v))
}

// GotifyTokenContains applies the Contains predicate on the "gotify_token" field.
func GotifyTokenContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldGotifyToken, v))
}

// GotifyTokenHasPrefix applies the HasPrefix predicate on the "gotify_token" field.
func GotifyTokenHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldGotifyToken, v))
}

// GotifyTokenHasSuffix applies the HasSuffix predicate on the "gotify_token" field.
func GotifyTokenHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldGotifyToken, v))
}

// GotifyTokenIsNil applies the IsNil predicate on the "gotify_token" field.
func GotifyTokenIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldGotifyToken))
}

// GotifyTokenNotNil applies the NotNil predicate on the "gotify_token" field.
func GotifyTokenNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldGotifyToken))
}

// GotifyTokenEqualFold applies the EqualFold predicate on the "gotify_token" field.
func GotifyTokenEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldGotifyToken, v))
}

// GotifyTokenContainsFold applies the ContainsFold predicate on the "gotify_token" field.
func GotifyTokenContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldGotifyToken, v))
}

// TelegramBotTokenEQ applies the EQ predicate on the "telegram_bot_token" field.
func TelegramBotTokenEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldTelegramBotToken, v))
}

// TelegramBotTokenNEQ applies the NEQ predicate on the "telegram_bot_token" field.
func TelegramBotTokenNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldTelegramBotToken, v))
}

// TelegramBotTokenIn applies the In predicate on the "telegram_bot_token" field.
func TelegramBotTokenIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldTelegramBotToken, vs...))
}

// TelegramBotTokenNotIn applies the NotIn predicate on the "telegram_bot_token" field.
func TelegramBotTokenNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldTelegramBotToken, vs...))
}

// TelegramBotTokenGT applies the GT predicate on the "telegram_bot_token" field.
func TelegramBotTokenGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldTelegramBotToken, v))
}

// TelegramBotTokenGTE applies the GTE predicate on the "telegram_bot_token" field.
func TelegramBotTokenGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldTelegramBotToken, v))
}

// TelegramBotTokenLT applies the LT predicate on the "telegram_bot_token" field.
func TelegramBotTokenLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldTelegramBotToken, v))
}

// TelegramBotTokenLTE applies the LTE predicate on the "telegram_bot_token" field.
func TelegramBotTokenLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldTelegramBotToken, v))
}

// TelegramBotTokenContains applies the Contains predicate on the "telegram_bot_token" field.
func TelegramBotTokenContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldTelegramBotToken, v))
}

// TelegramBotTokenHasPrefix applies the HasPrefix predicate on the "telegram_bot_token" field.
func TelegramBotTokenHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldTelegramBotToken, v))
}

// TelegramBotTokenHasSuffix applies the HasSuffix predicate on the "telegram_bot_token" field.
func TelegramBotTokenHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldTelegramBotToken, v))
}

// TelegramBotTokenIsNil applies the IsNil predicate on the "telegram_bot_token" field.
func TelegramBotTokenIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldTelegramBotToken))
}

// TelegramBotTokenNotNil applies the NotNil predicate on the "telegram_bot_token" field.
func TelegramBotTokenNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldTelegramBotToken))
}

// TelegramBotTokenEqualFold applies the EqualFold predicate on the "telegram_bot_token" field.
func TelegramBotTokenEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldTelegramBotToken, v))
}

// TelegramBotTokenContainsFold applies the ContainsFold predicate on the "telegram_bot_token" field.
func TelegramBotTokenContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldTelegramBotToken, v))
}

// TelegramChatIDEQ applies the EQ predicate on the "telegram_chat_id" field.
func TelegramChatIDEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldTelegramChatID, v))
}

// TelegramChatIDNEQ applies the NEQ predicate on the "telegram_chat_id" field.
func TelegramChatIDNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldTelegramChatID, v))
}

// TelegramChatIDIn applies the In predicate on the "telegram_chat_id" field.
func TelegramChatIDIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldTelegramChatID, vs...))
}

// TelegramChatIDNotIn applies the NotIn predicate on the "telegram_chat_id" field.
func TelegramChatIDNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldTelegramChatID, vs...))
}

// TelegramChatIDGT applies the GT predicate on the "telegram_chat_id" field.
func TelegramChatIDGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldTelegramChatID, v))
}

// TelegramChatIDGTE applies the GTE predicate on the "telegram_chat_id" field.
func TelegramChatIDGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldTelegramChatID, v))
}

// TelegramChatIDLT applies the LT predicate on the "telegram_chat_id" field.
func TelegramChatIDLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldTelegramChatID, v))
}

// TelegramChatIDLTE applies the LTE predicate on the "telegram_chat_id" field.
func TelegramChatIDLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldTelegramChatID, v))
}

// TelegramChatIDContains applies the Contains predicate on the "telegram_chat_id" field.
func TelegramChatIDContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldTelegramChatID, v))
}

// TelegramChatIDHasPrefix applies the HasPrefix predicate on the "telegram_chat_id" field.
func TelegramChatIDHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldTelegramChatID, v))
}

// TelegramChatIDHasSuffix applies the HasSuffix predicate on the "telegram_chat_id" field.
func TelegramChatIDHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldTelegramChatID, v))
}

// TelegramChatIDIsNil applies the IsNil predicate on the "telegram_chat_id" field.
func TelegramChatIDIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldTelegramChatID))
}

// TelegramChatIDNotNil applies the NotNil predicate on the "telegram_chat_id" field.
func TelegramChatIDNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldTelegramChatID))
}

// TelegramChatIDEqualFold applies the EqualFold predicate on the "telegram_chat_id" field.
func TelegramChatIDEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldTelegramChatID, v))
}

// TelegramChatIDContainsFold applies the ContainsFold predicate on the "telegram_chat_id" field.
func TelegramChatIDContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldTelegramChatID, v))
}

// UmamiURLEQ applies the EQ predicate on the "umami_url" field.
func UmamiURLEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldUmamiURL, v))
}

// UmamiURLNEQ applies the NEQ predicate on the "umami_url" field.
func UmamiURLNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldUmamiURL, v))
}

// UmamiURLIn applies the In predicate on the "umami_url" field.
func UmamiURLIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldUmamiURL, vs...))
}

// UmamiURLNotIn applies the NotIn predicate on the "umami_url" field.
func UmamiURLNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldUmamiURL, vs...))
}

// UmamiURLGT applies the GT predicate on the "umami_url" field.
func UmamiURLGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldUmamiURL, v))
}

// UmamiURLGTE applies the GTE predicate on the "umami_url" field.
func UmamiURLGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldUmamiURL, v))
}

// UmamiURLLT applies the LT predicate on the "umami_url" field.
func UmamiURLLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldUmamiURL, v))
}

// UmamiURLLTE applies the LTE predicate on the "umami_url" field.
func UmamiURLLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldUmamiURL, v))
}

// UmamiURLContains applies the Contains predicate on the "umami_url" field.
func UmamiURLContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldUmamiURL, v))
}

// UmamiURLHasPrefix applies the HasPrefix predicate on the "umami_url" field.
func UmamiURLHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldUmamiURL, v))
}

// UmamiURLHasSuffix applies the HasSuffix predicate on the "umami_url" field.
func UmamiURLHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldUmamiURL, v))
}

// UmamiURLIsNil applies the IsNil predicate on the "umami_url" field.
func UmamiURLIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldUmamiURL))
}

// UmamiURLNotNil applies the NotNil predicate on the "umami_url" field.
func UmamiURLNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldUmamiURL))
}

// UmamiURLEqualFold applies the EqualFold predicate on the "umami_url" field.
func UmamiURLEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldUmamiURL, v))
}

// UmamiURLContainsFold applies the ContainsFold predicate on the "umami_url" field.
func UmamiURLContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldUmamiURL, v))
}

// UmamiWebsiteIDEQ applies the EQ predicate on the "umami_website_id" field.
func UmamiWebsiteIDEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDNEQ applies the NEQ predicate on the "umami_website_id" field.
func UmamiWebsiteIDNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDIn applies the In predicate on the "umami_website_id" field.
func UmamiWebsiteIDIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldUmamiWebsiteID, vs...))
}

// UmamiWebsiteIDNotIn applies the NotIn predicate on the "umami_website_id" field.
func UmamiWebsiteIDNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldUmamiWebsiteID, vs...))
}

// UmamiWebsiteIDGT applies the GT predicate on the "umami_website_id" field.
func UmamiWebsiteIDGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDGTE applies the GTE predicate on the "umami_website_id" field.
func UmamiWebsiteIDGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDLT applies the LT predicate on the "umami_website_id" field.
func UmamiWebsiteIDLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDLTE applies the LTE predicate on the "umami_website_id" field.
func UmamiWebsiteIDLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDContains applies the Contains predicate on the "umami_website_id" field.
func UmamiWebsiteIDContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDHasPrefix applies the HasPrefix predicate on the "umami_website_id" field.
func UmamiWebsiteIDHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDHasSuffix applies the HasSuffix predicate on the "umami_website_id" field.
func UmamiWebsiteIDHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDIsNil applies the IsNil predicate on the "umami_website_id" field.
func UmamiWebsiteIDIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldUmamiWebsiteID))
}

// UmamiWebsiteIDNotNil applies the NotNil predicate on the "umami_website_id" field.
func UmamiWebsiteIDNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldUmamiWebsiteID))
}

// UmamiWebsiteIDEqualFold applies the EqualFold predicate on the "umami_website_id" field.
func UmamiWebsiteIDEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDContainsFold applies the ContainsFold predicate on the "umami_website_id" field.
func UmamiWebsiteIDContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldUmamiWebsiteID, v))
}

// EinkModeEQ applies the EQ predicate on the "eink_mode" field.
func EinkModeEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldEinkMode, v))
}

// EinkModeNEQ applies the NEQ predicate on the "eink_mode" field.
func EinkModeNEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldEinkMode, v))
}

// EinkModeIsNil applies the IsNil predicate on the "eink_mode" field.
func EinkModeIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldEinkMode))
}

// EinkModeNotNil applies the NotNil predicate on the "eink_mode" field.
func EinkModeNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldEinkMode))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.NotPredicates(p))
}
