// Code generated by ent, DO NOT EDIT.

package onetimenotification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datey/datey/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldID, id))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldMessage, v))
}

// ScheduledAt applies equality check predicate on the "scheduled_at" field. It's identical to ScheduledAtEQ.
func ScheduledAt(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldScheduledAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldCreatedAt, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldSentAt, v))
}

// ChannelTargets applies equality check predicate on the "channel_targets" field. It's identical to ChannelTargetsEQ.
func ChannelTargets(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldChannelTargets, v))
}

// PersonID applies equality check predicate on the "person_id" field. It's identical to PersonIDEQ.
func PersonID(v int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldPersonID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldEventType, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContainsFold(FieldMessage, v))
}

// ScheduledAtEQ applies the EQ predicate on the "scheduled_at" field.
func ScheduledAtEQ(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldScheduledAt, v))
}

// ScheduledAtNEQ applies the NEQ predicate on the "scheduled_at" field.
func ScheduledAtNEQ(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldScheduledAt, v))
}

// ScheduledAtIn applies the In predicate on the "scheduled_at" field.
func ScheduledAtIn(vs ...time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldScheduledAt, vs...))
}

// ScheduledAtNotIn applies the NotIn predicate on the "scheduled_at" field.
func ScheduledAtNotIn(vs ...time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldScheduledAt, vs...))
}

// ScheduledAtGT applies the GT predicate on the "scheduled_at" field.
func ScheduledAtGT(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldScheduledAt, v))
}

// ScheduledAtGTE applies the GTE predicate on the "scheduled_at" field.
func ScheduledAtGTE(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldScheduledAt, v))
}

// ScheduledAtLT applies the LT predicate on the "scheduled_at" field.
func ScheduledAtLT(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldScheduledAt, v))
}

// ScheduledAtLTE applies the LTE predicate on the "scheduled_at" field.
func ScheduledAtLTE(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldScheduledAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldCreatedAt, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotNull(FieldSentAt))
}

// ChannelTargetsEQ applies the EQ predicate on the "channel_targets" field.
func ChannelTargetsEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldChannelTargets, v))
}

// ChannelTargetsNEQ applies the NEQ predicate on the "channel_targets" field.
func ChannelTargetsNEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldChannelTargets, v))
}

// ChannelTargetsIn applies the In predicate on the "channel_targets" field.
func ChannelTargetsIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldChannelTargets, vs...))
}

// ChannelTargetsNotIn applies the NotIn predicate on the "channel_targets" field.
func ChannelTargetsNotIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldChannelTargets, vs...))
}

// ChannelTargetsGT applies the GT predicate on the "channel_targets" field.
func ChannelTargetsGT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldChannelTargets, v))
}

// ChannelTargetsGTE applies the GTE predicate on the "channel_targets" field.
func ChannelTargetsGTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldChannelTargets, v))
}

// ChannelTargetsLT applies the LT predicate on the "channel_targets" field.
func ChannelTargetsLT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldChannelTargets, v))
}

// ChannelTargetsLTE applies the LTE predicate on the "channel_targets" field.
func ChannelTargetsLTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldChannelTargets, v))
}

// ChannelTargetsContains applies the Contains predicate on the "channel_targets" field.
func ChannelTargetsContains(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContains(FieldChannelTargets, v))
}

// ChannelTargetsHasPrefix applies the HasPrefix predicate on the "channel_targets" field.
func ChannelTargetsHasPrefix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasPrefix(FieldChannelTargets, v))
}

// ChannelTargetsHasSuffix applies the HasSuffix predicate on the "channel_targets" field.
func ChannelTargetsHasSuffix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasSuffix(FieldChannelTargets, v))
}

// ChannelTargetsIsNil applies the IsNil predicate on the "channel_targets" field.
func ChannelTargetsIsNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIsNull(FieldChannelTargets))
}

// ChannelTargetsNotNil applies the NotNil predicate on the "channel_targets" field.
func ChannelTargetsNotNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotNull(FieldChannelTargets))
}

// ChannelTargetsEqualFold applies the EqualFold predicate on the "channel_targets" field.
func ChannelTargetsEqualFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEqualFold(FieldChannelTargets, v))
}

// ChannelTargetsContainsFold applies the ContainsFold predicate on the "channel_targets" field.
func ChannelTargetsContainsFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContainsFold(FieldChannelTargets, v))
}

// PersonIDEQ applies the EQ predicate on the "person_id" field.
func PersonIDEQ(v int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldPersonID, v))
}

// PersonIDNEQ applies the NEQ predicate on the "person_id" field.
func PersonIDNEQ(v int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldPersonID, v))
}

// PersonIDIn applies the In predicate on the "person_id" field.
func PersonIDIn(vs ...int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldPersonID, vs...))
}

// PersonIDNotIn applies the NotIn predicate on the "person_id" field.
func PersonIDNotIn(vs ...int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldPersonID, vs...))
}

// PersonIDGT applies the GT predicate on the "person_id" field.
func PersonIDGT(v int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldPersonID, v))
}

// PersonIDGTE applies the GTE predicate on the "person_id" field.
func PersonIDGTE(v int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldPersonID, v))
}

// PersonIDLT applies the LT predicate on the "person_id" field.
func PersonIDLT(v int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldPersonID, v))
}

// PersonIDLTE applies the LTE predicate on the "person_id" field.
func PersonIDLTE(v int) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldPersonID, v))
}

// PersonIDIsNil applies the IsNil predicate on the "person_id" field.
func PersonIDIsNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIsNull(FieldPersonID))
}

// PersonIDNotNil applies the NotNil predicate on the "person_id" field.
func PersonIDNotNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotNull(FieldPersonID))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeIsNil applies the IsNil predicate on the "event_type" field.
func EventTypeIsNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldIsNull(FieldEventType))
}

// EventTypeNotNil applies the NotNil predicate on the "event_type" field.
func EventTypeNotNil() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldNotNull(FieldEventType))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.FieldContainsFold(FieldEventType, v))
}

// HasDeliveries applies the HasEdge predicate on the "deliveries" edge.
func HasDeliveries() predicate.OneTimeNotification {
	return predicate.OneTimeNotification(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeliveriesTable, DeliveriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeliveriesWith applies the HasEdge predicate on the "deliveries" edge with a given conditions (other predicates).
func HasDeliveriesWith(preds ...predicate.NotificationDelivery) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(func(s *sql.Selector) {
		step := newDeliveriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OneTimeNotification) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OneTimeNotification) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OneTimeNotification) predicate.OneTimeNotification {
	return predicate.OneTimeNotification(sql.NotPredicates(p))
}
