// Code generated by ent, DO NOT EDIT.

package usernotificationchannel

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datey/datey/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldLTE(FieldID, id))
}

// ChannelType applies equality check predicate on the "channel_type" field. It's identical to ChannelTypeEQ.
func ChannelType(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldChannelType, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldTarget, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldEnabled, v))
}

// ChannelTypeEQ applies the EQ predicate on the "channel_type" field.
func ChannelTypeEQ(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldChannelType, v))
}

// ChannelTypeNEQ applies the NEQ predicate on the "channel_type" field.
func ChannelTypeNEQ(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNEQ(FieldChannelType, v))
}

// ChannelTypeIn applies the In predicate on the "channel_type" field.
func ChannelTypeIn(vs ...string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldIn(FieldChannelType, vs...))
}

// ChannelTypeNotIn applies the NotIn predicate on the "channel_type" field.
func ChannelTypeNotIn(vs ...string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNotIn(FieldChannelType, vs...))
}

// ChannelTypeGT applies the GT predicate on the "channel_type" field.
func ChannelTypeGT(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldGT(FieldChannelType, v))
}

// ChannelTypeGTE applies the GTE predicate on the "channel_type" field.
func ChannelTypeGTE(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldGTE(FieldChannelType, v))
}

// ChannelTypeLT applies the LT predicate on the "channel_type" field.
func ChannelTypeLT(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldLT(FieldChannelType, v))
}

// ChannelTypeLTE applies the LTE predicate on the "channel_type" field.
func ChannelTypeLTE(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldLTE(FieldChannelType, v))
}

// ChannelTypeContains applies the Contains predicate on the "channel_type" field.
func ChannelTypeContains(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldContains(FieldChannelType, v))
}

// ChannelTypeHasPrefix applies the HasPrefix predicate on the "channel_type" field.
func ChannelTypeHasPrefix(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldHasPrefix(FieldChannelType, v))
}

// ChannelTypeHasSuffix applies the HasSuffix predicate on the "channel_type" field.
func ChannelTypeHasSuffix(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldHasSuffix(FieldChannelType, v))
}

// ChannelTypeEqualFold applies the EqualFold predicate on the "channel_type" field.
func ChannelTypeEqualFold(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEqualFold(FieldChannelType, v))
}

// ChannelTypeContainsFold applies the ContainsFold predicate on the "channel_type" field.
func ChannelTypeContainsFold(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldContainsFold(FieldChannelType, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetIsNil applies the IsNil predicate on the "target" field.
func TargetIsNil() predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldIsNull(FieldTarget))
}

// TargetNotNil applies the NotNil predicate on the "target" field.
func TargetNotNil() predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNotNull(FieldTarget))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldContainsFold(FieldTarget, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.FieldNEQ(FieldEnabled, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserNotificationChannel) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserNotificationChannel) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserNotificationChannel) predicate.UserNotificationChannel {
	return predicate.UserNotificationChannel(sql.NotPredicates(p))
}
