// Code generated by ent, DO NOT EDIT.

package auditentry

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditentry type in the database.
	Label = "audit_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldActorUsername holds the string denoting the actor_username field in the database.
	FieldActorUsername = "actor_username"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldSourceIP holds the string denoting the source_ip field in the database.
	FieldSourceIP = "source_ip"
	// Table holds the table name of the auditentry in the database.
	Table = "audit_entries"
)

// Columns holds all SQL columns for auditentry fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldActorUsername,
	FieldAction,
	FieldTarget,
	FieldSourceIP,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActorUsernameValidator is a validator for the "actor_username" field. It is called by the builders before save.
	ActorUsernameValidator func(string) error
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultTarget holds the default value on creation for the "target" field.
	DefaultTarget string
	// TargetValidator is a validator for the "target" field. It is called by the builders before save.
	TargetValidator func(string) error
	// DefaultSourceIP holds the default value on creation for the "source_ip" field.
	DefaultSourceIP string
)

// OrderOption defines the ordering options for the AuditEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByActorUsername orders the results by the actor_username field.
func ByActorUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUsername, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// BySourceIP orders the results by the source_ip field.
func BySourceIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceIP, opts...).ToFunc()
}
