// Code generated by ent, DO NOT EDIT.

package recurringrule

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the recurringrule type in the database.
	Label = "recurring_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPatternType holds the string denoting the pattern_type field in the database.
	FieldPatternType = "pattern_type"
	// FieldNth holds the string denoting the nth field in the database.
	FieldNth = "nth"
	// FieldWeekday holds the string denoting the weekday field in the database.
	FieldWeekday = "weekday"
	// FieldMonth holds the string denoting the month field in the database.
	FieldMonth = "month"
	// FieldDay holds the string denoting the day field in the database.
	FieldDay = "day"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the recurringrule in the database.
	Table = "recurring_rules"
)

// Columns holds all SQL columns for recurringrule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPatternType,
	FieldNth,
	FieldWeekday,
	FieldMonth,
	FieldDay,
	FieldEnabled,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PatternTypeValidator is a validator for the "pattern_type" field. It is called by the builders before save.
	PatternTypeValidator func(string) error
	// DefaultNth holds the default value on creation for the "nth" field.
	DefaultNth int
	// DefaultWeekday holds the default value on creation for the "weekday" field.
	DefaultWeekday int
	// DefaultMonth holds the default value on creation for the "month" field.
	DefaultMonth int
	// DefaultDay holds the default value on creation for the "day" field.
	DefaultDay int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the RecurringRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPatternType orders the results by the pattern_type field.
func ByPatternType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatternType, opts...).ToFunc()
}

// ByNth orders the results by the nth field.
func ByNth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNth, opts...).ToFunc()
}

// ByWeekday orders the results by the weekday field.
func ByWeekday(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeekday, opts...).ToFunc()
}

// ByMonth orders the results by the month field.
func ByMonth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonth, opts...).ToFunc()
}

// ByDay orders the results by the day field.
func ByDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDay, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
