// Code generated by ent, DO NOT EDIT.

package recurringrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/datey/datey/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldName, v))
}

// PatternType applies equality check predicate on the "pattern_type" field. It's identical to PatternTypeEQ.
func PatternType(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldPatternType, v))
}

// Nth applies equality check predicate on the "nth" field. It's identical to NthEQ.
func Nth(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldNth, v))
}

// Weekday applies equality check predicate on the "weekday" field. It's identical to WeekdayEQ.
func Weekday(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldWeekday, v))
}

// Month applies equality check predicate on the "month" field. It's identical to MonthEQ.
func Month(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldMonth, v))
}

// Day applies equality check predicate on the "day" field. It's identical to DayEQ.
func Day(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldDay, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldContainsFold(FieldName, v))
}

// PatternTypeEQ applies the EQ predicate on the "pattern_type" field.
func PatternTypeEQ(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldPatternType, v))
}

// PatternTypeNEQ applies the NEQ predicate on the "pattern_type" field.
func PatternTypeNEQ(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldPatternType, v))
}

// PatternTypeIn applies the In predicate on the "pattern_type" field.
func PatternTypeIn(vs ...string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldPatternType, vs...))
}

// PatternTypeNotIn applies the NotIn predicate on the "pattern_type" field.
func PatternTypeNotIn(vs ...string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldPatternType, vs...))
}

// PatternTypeGT applies the GT predicate on the "pattern_type" field.
func PatternTypeGT(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldPatternType, v))
}

// PatternTypeGTE applies the GTE predicate on the "pattern_type" field.
func PatternTypeGTE(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldPatternType, v))
}

// PatternTypeLT applies the LT predicate on the "pattern_type" field.
func PatternTypeLT(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldPatternType, v))
}

// PatternTypeLTE applies the LTE predicate on the "pattern_type" field.
func PatternTypeLTE(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldPatternType, v))
}

// PatternTypeContains applies the Contains predicate on the "pattern_type" field.
func PatternTypeContains(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldContains(FieldPatternType, v))
}

// PatternTypeHasPrefix applies the HasPrefix predicate on the "pattern_type" field.
func PatternTypeHasPrefix(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldHasPrefix(FieldPatternType, v))
}

// PatternTypeHasSuffix applies the HasSuffix predicate on the "pattern_type" field.
func PatternTypeHasSuffix(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldHasSuffix(FieldPatternType, v))
}

// PatternTypeEqualFold applies the EqualFold predicate on the "pattern_type" field.
func PatternTypeEqualFold(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEqualFold(FieldPatternType, v))
}

// PatternTypeContainsFold applies the ContainsFold predicate on the "pattern_type" field.
func PatternTypeContainsFold(v string) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldContainsFold(FieldPatternType, v))
}

// NthEQ applies the EQ predicate on the "nth" field.
func NthEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldNth, v))
}

// NthNEQ applies the NEQ predicate on the "nth" field.
func NthNEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldNth, v))
}

// NthIn applies the In predicate on the "nth" field.
func NthIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldNth, vs...))
}

// NthNotIn applies the NotIn predicate on the "nth" field.
func NthNotIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldNth, vs...))
}

// NthGT applies the GT predicate on the "nth" field.
func NthGT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldNth, v))
}

// NthGTE applies the GTE predicate on the "nth" field.
func NthGTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldNth, v))
}

// NthLT applies the LT predicate on the "nth" field.
func NthLT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldNth, v))
}

// NthLTE applies the LTE predicate on the "nth" field.
func NthLTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldNth, v))
}

// NthIsNil applies the IsNil predicate on the "nth" field.
func NthIsNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIsNull(FieldNth))
}

// NthNotNil applies the NotNil predicate on the "nth" field.
func NthNotNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotNull(FieldNth))
}

// WeekdayEQ applies the EQ predicate on the "weekday" field.
func WeekdayEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldWeekday, v))
}

// WeekdayNEQ applies the NEQ predicate on the "weekday" field.
func WeekdayNEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldWeekday, v))
}

// WeekdayIn applies the In predicate on the "weekday" field.
func WeekdayIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldWeekday, vs...))
}

// WeekdayNotIn applies the NotIn predicate on the "weekday" field.
func WeekdayNotIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldWeekday, vs...))
}

// WeekdayGT applies the GT predicate on the "weekday" field.
func WeekdayGT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldWeekday, v))
}

// WeekdayGTE applies the GTE predicate on the "weekday" field.
func WeekdayGTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldWeekday, v))
}

// WeekdayLT applies the LT predicate on the "weekday" field.
func WeekdayLT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldWeekday, v))
}

// WeekdayLTE applies the LTE predicate on the "weekday" field.
func WeekdayLTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldWeekday, v))
}

// WeekdayIsNil applies the IsNil predicate on the "weekday" field.
func WeekdayIsNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIsNull(FieldWeekday))
}

// WeekdayNotNil applies the NotNil predicate on the "weekday" field.
func WeekdayNotNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotNull(FieldWeekday))
}

// MonthEQ applies the EQ predicate on the "month" field.
func MonthEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldMonth, v))
}

// MonthNEQ applies the NEQ predicate on the "month" field.
func MonthNEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldMonth, v))
}

// MonthIn applies the In predicate on the "month" field.
func MonthIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldMonth, vs...))
}

// MonthNotIn applies the NotIn predicate on the "month" field.
func MonthNotIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldMonth, vs...))
}

// MonthGT applies the GT predicate on the "month" field.
func MonthGT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldMonth, v))
}

// MonthGTE applies the GTE predicate on the "month" field.
func MonthGTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldMonth, v))
}

// MonthLT applies the LT predicate on the "month" field.
func MonthLT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldMonth, v))
}

// MonthLTE applies the LTE predicate on the "month" field.
func MonthLTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldMonth, v))
}

// MonthIsNil applies the IsNil predicate on the "month" field.
func MonthIsNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIsNull(FieldMonth))
}

// MonthNotNil applies the NotNil predicate on the "month" field.
func MonthNotNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotNull(FieldMonth))
}

// DayEQ applies the EQ predicate on the "day" field.
func DayEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldDay, v))
}

// DayNEQ applies the NEQ predicate on the "day" field.
func DayNEQ(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldDay, v))
}

// DayIn applies the In predicate on the "day" field.
func DayIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldDay, vs...))
}

// DayNotIn applies the NotIn predicate on the "day" field.
func DayNotIn(vs ...int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldDay, vs...))
}

// DayGT applies the GT predicate on the "day" field.
func DayGT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldDay, v))
}

// DayGTE applies the GTE predicate on the "day" field.
func DayGTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldDay, v))
}

// DayLT applies the LT predicate on the "day" field.
func DayLT(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldDay, v))
}

// DayLTE applies the LTE predicate on the "day" field.
func DayLTE(v int) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldDay, v))
}

// DayIsNil applies the IsNil predicate on the "day" field.
func DayIsNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIsNull(FieldDay))
}

// DayNotNil applies the NotNil predicate on the "day" field.
func DayNotNil() predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotNull(FieldDay))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RecurringRule {
	return predicate.RecurringRule(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecurringRule) predicate.RecurringRule {
	return predicate.RecurringRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecurringRule) predicate.RecurringRule {
	return predicate.RecurringRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecurringRule) predicate.RecurringRule {
	return predicate.RecurringRule(sql.NotPredicates(p))
}
