// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppConfigsColumns holds the columns for the "app_configs" table.
	AppConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "port", Type: field.TypeInt, Nullable: true},
		{Name: "data_dir", Type: field.TypeString, Nullable: true},
		{Name: "scheduler_hour", Type: field.TypeInt, Nullable: true},
		{Name: "reminder_days", Type: field.TypeInt, Nullable: true},
		{Name: "last_scheduler_run", Type: field.TypeTime, Nullable: true},
		{Name: "scheduler_catchup", Type: field.TypeBool, Nullable: true},
		{Name: "date_variant", Type: field.TypeString, Nullable: true},
		{Name: "reminder_digest", Type: field.TypeBool, Nullable: true},
		{Name: "reminder_stages", Type: field.TypeString, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Nullable: true},
		{Name: "log_level", Type: field.TypeString, Nullable: true},
		{Name: "log_buffer_size", Type: field.TypeInt, Nullable: true},
		{Name: "otel_endpoint", Type: field.TypeString, Nullable: true},
		{Name: "backup_dir", Type: field.TypeString, Nullable: true},
		{Name: "backup_retention_days", Type: field.TypeInt, Nullable: true},
		{Name: "smtp_host", Type: field.TypeString, Nullable: true},
		{Name: "smtp_port", Type: field.TypeInt, Nullable: true},
		{Name: "smtp_user", Type: field.TypeString, Nullable: true},
		{Name: "smtp_pass", Type: field.TypeString, Nullable: true},
		{Name: "smtp_tls", Type: field.TypeBool, Nullable: true},
		{Name: "smtp_timeout", Type: field.TypeInt, Nullable: true},
		{Name: "notify_email", Type: field.TypeString, Nullable: true},
		{Name: "gotify_url", Type: field.TypeString, Nullable: true},
		{Name: "gotify_token", Type: field.TypeString, Nullable: true},
		{Name: "telegram_bot_token", Type: field.TypeString, Nullable: true},
		{Name: "telegram_chat_id", Type: field.TypeString, Nullable: true},
		{Name: "ntfy_url", Type: field.TypeString, Nullable: true},
		{Name: "ntfy_topic", Type: field.TypeString, Nullable: true},
		{Name: "ntfy_token", Type: field.TypeString, Nullable: true},
		{Name: "ntfy_priority", Type: field.TypeInt, Nullable: true},
		{Name: "webhook_url", Type: field.TypeString, Nullable: true},
		{Name: "webhook_secret", Type: field.TypeString, Nullable: true},
		{Name: "discord_webhook_url", Type: field.TypeString, Nullable: true},
		{Name: "slack_webhook_url", Type: field.TypeString, Nullable: true},
		{Name: "matrix_homeserver_url", Type: field.TypeString, Nullable: true},
		{Name: "matrix_access_token", Type: field.TypeString, Nullable: true},
		{Name: "matrix_room_id", Type: field.TypeString, Nullable: true},
		{Name: "umami_url", Type: field.TypeString, Nullable: true},
		{Name: "umami_website_id", Type: field.TypeString, Nullable: true},
		{Name: "eink_mode", Type: field.TypeBool, Nullable: true},
		{Name: "ical_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "ical_event_start", Type: field.TypeString, Nullable: true},
		{Name: "ical_duration_minutes", Type: field.TypeInt, Nullable: true},
		{Name: "ical_feed_key", Type: field.TypeString, Nullable: true},
		{Name: "rss_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "rss_feed_key", Type: field.TypeString, Nullable: true},
		{Name: "upcoming_api_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "upcoming_api_key", Type: field.TypeString, Nullable: true},
		{Name: "homeassistant_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "homeassistant_key", Type: field.TypeString, Nullable: true},
		{Name: "push_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "push_vapid_public_key", Type: field.TypeString, Nullable: true},
		{Name: "push_vapid_private_key", Type: field.TypeString, Nullable: true},
		{Name: "immich_url", Type: field.TypeString, Nullable: true},
		{Name: "immich_api_key", Type: field.TypeString, Nullable: true},
		{Name: "carddav_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "carddav_url", Type: field.TypeString, Nullable: true},
		{Name: "carddav_username", Type: field.TypeString, Nullable: true},
		{Name: "carddav_password", Type: field.TypeString, Nullable: true},
		{Name: "carddav_sync_token", Type: field.TypeString, Nullable: true},
		{Name: "carddav_last_sync", Type: field.TypeTime, Nullable: true},
		{Name: "carddav_delete_policy", Type: field.TypeString, Nullable: true},
		{Name: "google_contacts_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "google_client_id", Type: field.TypeString, Nullable: true},
		{Name: "google_client_secret", Type: field.TypeString, Nullable: true},
		{Name: "google_refresh_token", Type: field.TypeString, Nullable: true},
		{Name: "google_sync_token", Type: field.TypeString, Nullable: true},
		{Name: "google_last_sync", Type: field.TypeTime, Nullable: true},
		{Name: "google_delete_policy", Type: field.TypeString, Nullable: true},
		{Name: "google_oauth_state", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "audit_retention_max", Type: field.TypeInt, Nullable: true},
	}
	// AppConfigsTable holds the schema information for the "app_configs" table.
	AppConfigsTable = &schema.Table{
		Name:       "app_configs",
		Columns:    AppConfigsColumns,
		PrimaryKey: []*schema.Column{AppConfigsColumns[0]},
	}
	// AuditEntriesColumns holds the columns for the "audit_entries" table.
	AuditEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "actor_username", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "target", Type: field.TypeString, Default: ""},
		{Name: "source_ip", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// AuditEntriesTable holds the schema information for the "audit_entries" table.
	AuditEntriesTable = &schema.Table{
		Name:       "audit_entries",
		Columns:    AuditEntriesColumns,
		PrimaryKey: []*schema.Column{AuditEntriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditentry_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditEntriesColumns[1]},
			},
			{
				Name:    "auditentry_action",
				Unique:  false,
				Columns: []*schema.Column{AuditEntriesColumns[3]},
			},
		},
	}
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "reminder_days", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "calendar_system", Type: field.TypeString, Default: "gregorian"},
		{Name: "lunar_month", Type: field.TypeInt, Nullable: true},
		{Name: "lunar_day", Type: field.TypeInt, Nullable: true},
		{Name: "lunar_leap", Type: field.TypeBool, Default: false},
		{Name: "contact_events", Type: field.TypeInt, Nullable: true},
		{Name: "group_events", Type: field.TypeInt, Nullable: true},
		{Name: "person_events", Type: field.TypeInt, Nullable: true},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_contacts_events",
				Columns:    []*schema.Column{EventsColumns[11]},
				RefColumns: []*schema.Column{ContactsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "events_groups_events",
				Columns:    []*schema.Column{EventsColumns[12]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "events_persons_events",
				Columns:    []*schema.Column{EventsColumns[13]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "event_date",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[2]},
			},
			{
				Name:    "event_type",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[1]},
			},
		},
	}
	// GiftIdeasColumns holds the columns for the "gift_ideas" table.
	GiftIdeasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "price_cents", Type: field.TypeInt, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"idea", "purchased", "given", "archived"}, Default: "idea"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "person_gift_ideas", Type: field.TypeInt},
	}
	// GiftIdeasTable holds the schema information for the "gift_ideas" table.
	GiftIdeasTable = &schema.Table{
		Name:       "gift_ideas",
		Columns:    GiftIdeasColumns,
		PrimaryKey: []*schema.Column{GiftIdeasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "gift_ideas_persons_giftIdeas",
				Columns:    []*schema.Column{GiftIdeasColumns[8]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "giftidea_status_person_gift_ideas",
				Unique:  false,
				Columns: []*schema.Column{GiftIdeasColumns[5], GiftIdeasColumns[8]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
	}
	// GroupNotesColumns holds the columns for the "group_notes" table.
	GroupNotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "note", Type: field.TypeString, Size: 2147483647},
		{Name: "note_date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "group_notes", Type: field.TypeInt},
	}
	// GroupNotesTable holds the schema information for the "group_notes" table.
	GroupNotesTable = &schema.Table{
		Name:       "group_notes",
		Columns:    GroupNotesColumns,
		PrimaryKey: []*schema.Column{GroupNotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_notes_groups_notes",
				Columns:    []*schema.Column{GroupNotesColumns[5]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MigrationLogsColumns holds the columns for the "migration_logs" table.
	MigrationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "applied_at", Type: field.TypeTime},
	}
	// MigrationLogsTable holds the schema information for the "migration_logs" table.
	MigrationLogsTable = &schema.Table{
		Name:       "migration_logs",
		Columns:    MigrationLogsColumns,
		PrimaryKey: []*schema.Column{MigrationLogsColumns[0]},
	}
	// NotificationLogsColumns holds the columns for the "notification_logs" table.
	NotificationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel", Type: field.TypeString},
		{Name: "sent_at", Type: field.TypeTime},
		{Name: "date_key", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "event_notification_logs", Type: field.TypeInt},
	}
	// NotificationLogsTable holds the schema information for the "notification_logs" table.
	NotificationLogsTable = &schema.Table{
		Name:       "notification_logs",
		Columns:    NotificationLogsColumns,
		PrimaryKey: []*schema.Column{NotificationLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_logs_events_notification_logs",
				Columns:    []*schema.Column{NotificationLogsColumns[5]},
				RefColumns: []*schema.Column{EventsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notificationlog_channel_date_key",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[1], NotificationLogsColumns[3]},
			},
			{
				Name:    "notificationlog_channel_date_key_user_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[1], NotificationLogsColumns[3], NotificationLogsColumns[4]},
			},
		},
	}
	// PasswordResetTokensColumns holds the columns for the "password_reset_tokens" table.
	PasswordResetTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "used", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_password_reset_tokens", Type: field.TypeInt},
	}
	// PasswordResetTokensTable holds the schema information for the "password_reset_tokens" table.
	PasswordResetTokensTable = &schema.Table{
		Name:       "password_reset_tokens",
		Columns:    PasswordResetTokensColumns,
		PrimaryKey: []*schema.Column{PasswordResetTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "password_reset_tokens_users_password_reset_tokens",
				Columns:    []*schema.Column{PasswordResetTokensColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PersonsColumns holds the columns for the "persons" table.
	PersonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "middle_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "vcard_data", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "notify_birthdays", Type: field.TypeBool, Default: true},
		{Name: "timezone", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "reminder_days", Type: field.TypeJSON, Nullable: true},
		{Name: "immich_person_id", Type: field.TypeString, Nullable: true},
		{Name: "immich_photo_disabled", Type: field.TypeBool, Default: false},
		{Name: "photo_path", Type: field.TypeString, Nullable: true},
		{Name: "photo_content_type", Type: field.TypeString, Nullable: true},
		{Name: "photo_updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "photo_source", Type: field.TypeString, Nullable: true},
		{Name: "carddav_uid", Type: field.TypeString, Nullable: true},
		{Name: "carddav_href", Type: field.TypeString, Nullable: true},
		{Name: "carddav_etag", Type: field.TypeString, Nullable: true},
		{Name: "carddav_rev", Type: field.TypeString, Nullable: true},
		{Name: "carddav_last_modified", Type: field.TypeTime, Nullable: true},
		{Name: "carddav_pending_sync", Type: field.TypeBool, Default: false},
		{Name: "google_resource_name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PersonsTable holds the schema information for the "persons" table.
	PersonsTable = &schema.Table{
		Name:       "persons",
		Columns:    PersonsColumns,
		PrimaryKey: []*schema.Column{PersonsColumns[0]},
	}
	// PersonNotesColumns holds the columns for the "person_notes" table.
	PersonNotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "note", Type: field.TypeString, Size: 2147483647},
		{Name: "note_date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "person_timeline", Type: field.TypeInt},
	}
	// PersonNotesTable holds the schema information for the "person_notes" table.
	PersonNotesTable = &schema.Table{
		Name:       "person_notes",
		Columns:    PersonNotesColumns,
		PrimaryKey: []*schema.Column{PersonNotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "person_notes_persons_timeline",
				Columns:    []*schema.Column{PersonNotesColumns[5]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PushSubscriptionsColumns holds the columns for the "push_subscriptions" table.
	PushSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "endpoint", Type: field.TypeString, Unique: true},
		{Name: "p256dh", Type: field.TypeString},
		{Name: "auth", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_push_subscriptions", Type: field.TypeInt},
	}
	// PushSubscriptionsTable holds the schema information for the "push_subscriptions" table.
	PushSubscriptionsTable = &schema.Table{
		Name:       "push_subscriptions",
		Columns:    PushSubscriptionsColumns,
		PrimaryKey: []*schema.Column{PushSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "push_subscriptions_users_push_subscriptions",
				Columns:    []*schema.Column{PushSubscriptionsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RecurringRulesColumns holds the columns for the "recurring_rules" table.
	RecurringRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "pattern_type", Type: field.TypeString},
		{Name: "nth", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "weekday", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "month", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "day", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RecurringRulesTable holds the schema information for the "recurring_rules" table.
	RecurringRulesTable = &schema.Table{
		Name:       "recurring_rules",
		Columns:    RecurringRulesColumns,
		PrimaryKey: []*schema.Column{RecurringRulesColumns[0]},
	}
	// RelationshipsColumns holds the columns for the "relationships" table.
	RelationshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"partner", "parent", "sibling", "custom"}},
		{Name: "label", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "from_id", Type: field.TypeInt},
		{Name: "to_id", Type: field.TypeInt},
	}
	// RelationshipsTable holds the schema information for the "relationships" table.
	RelationshipsTable = &schema.Table{
		Name:       "relationships",
		Columns:    RelationshipsColumns,
		PrimaryKey: []*schema.Column{RelationshipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relationships_persons_outgoing_relationships",
				Columns:    []*schema.Column{RelationshipsColumns[3]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "relationships_persons_incoming_relationships",
				Columns:    []*schema.Column{RelationshipsColumns[4]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relationship_from_id",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[3]},
			},
			{
				Name:    "relationship_to_id",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[4]},
			},
			{
				Name:    "relationship_from_id_to_id_type",
				Unique:  true,
				Columns: []*schema.Column{RelationshipsColumns[3], RelationshipsColumns[4], RelationshipsColumns[1]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "eink_mode", Type: field.TypeBool, Default: false},
		{Name: "locale", Type: field.TypeString, Nullable: true},
		{Name: "notification_scope_mode", Type: field.TypeEnum, Enums: []string{"all", "selected"}, Default: "all"},
		{Name: "notification_scope_group_ids", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserNotificationChannelsColumns holds the columns for the "user_notification_channels" table.
	UserNotificationChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel_type", Type: field.TypeString},
		{Name: "target", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "user_notification_channels", Type: field.TypeInt},
	}
	// UserNotificationChannelsTable holds the schema information for the "user_notification_channels" table.
	UserNotificationChannelsTable = &schema.Table{
		Name:       "user_notification_channels",
		Columns:    UserNotificationChannelsColumns,
		PrimaryKey: []*schema.Column{UserNotificationChannelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_notification_channels_users_notification_channels",
				Columns:    []*schema.Column{UserNotificationChannelsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usernotificationchannel_channel_type_user_notification_channels",
				Unique:  true,
				Columns: []*schema.Column{UserNotificationChannelsColumns[1], UserNotificationChannelsColumns[4]},
			},
		},
	}
	// PersonGroupsColumns holds the columns for the "person_groups" table.
	PersonGroupsColumns = []*schema.Column{
		{Name: "person_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// PersonGroupsTable holds the schema information for the "person_groups" table.
	PersonGroupsTable = &schema.Table{
		Name:       "person_groups",
		Columns:    PersonGroupsColumns,
		PrimaryKey: []*schema.Column{PersonGroupsColumns[0], PersonGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "person_groups_person_id",
				Columns:    []*schema.Column{PersonGroupsColumns[0]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "person_groups_group_id",
				Columns:    []*schema.Column{PersonGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PersonTagsColumns holds the columns for the "person_tags" table.
	PersonTagsColumns = []*schema.Column{
		{Name: "person_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// PersonTagsTable holds the schema information for the "person_tags" table.
	PersonTagsTable = &schema.Table{
		Name:       "person_tags",
		Columns:    PersonTagsColumns,
		PrimaryKey: []*schema.Column{PersonTagsColumns[0], PersonTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "person_tags_person_id",
				Columns:    []*schema.Column{PersonTagsColumns[0]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "person_tags_tag_id",
				Columns:    []*schema.Column{PersonTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppConfigsTable,
		AuditEntriesTable,
		ContactsTable,
		EventsTable,
		GiftIdeasTable,
		GroupsTable,
		GroupNotesTable,
		MigrationLogsTable,
		NotificationLogsTable,
		PasswordResetTokensTable,
		PersonsTable,
		PersonNotesTable,
		PushSubscriptionsTable,
		RecurringRulesTable,
		RelationshipsTable,
		SessionsTable,
		TagsTable,
		UsersTable,
		UserNotificationChannelsTable,
		PersonGroupsTable,
		PersonTagsTable,
	}
)

func init() {
	EventsTable.ForeignKeys[0].RefTable = ContactsTable
	EventsTable.ForeignKeys[1].RefTable = GroupsTable
	EventsTable.ForeignKeys[2].RefTable = PersonsTable
	GiftIdeasTable.ForeignKeys[0].RefTable = PersonsTable
	GroupNotesTable.ForeignKeys[0].RefTable = GroupsTable
	NotificationLogsTable.ForeignKeys[0].RefTable = EventsTable
	PasswordResetTokensTable.ForeignKeys[0].RefTable = UsersTable
	PersonNotesTable.ForeignKeys[0].RefTable = PersonsTable
	PushSubscriptionsTable.ForeignKeys[0].RefTable = UsersTable
	RelationshipsTable.ForeignKeys[0].RefTable = PersonsTable
	RelationshipsTable.ForeignKeys[1].RefTable = PersonsTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	UserNotificationChannelsTable.ForeignKeys[0].RefTable = UsersTable
	PersonGroupsTable.ForeignKeys[0].RefTable = PersonsTable
	PersonGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	PersonTagsTable.ForeignKeys[0].RefTable = PersonsTable
	PersonTagsTable.ForeignKeys[1].RefTable = TagsTable
}
