// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "contact_events", Type: field.TypeInt},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_contacts_events",
				Columns:    []*schema.Column{EventsColumns[5]},
				RefColumns: []*schema.Column{ContactsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "event_date",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[2]},
			},
			{
				Name:    "event_type",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[1]},
			},
		},
	}
	// NotificationLogsColumns holds the columns for the "notification_logs" table.
	NotificationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel", Type: field.TypeString},
		{Name: "sent_at", Type: field.TypeTime},
		{Name: "date_key", Type: field.TypeString},
		{Name: "event_notification_logs", Type: field.TypeInt},
	}
	// NotificationLogsTable holds the schema information for the "notification_logs" table.
	NotificationLogsTable = &schema.Table{
		Name:       "notification_logs",
		Columns:    NotificationLogsColumns,
		PrimaryKey: []*schema.Column{NotificationLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_logs_events_notification_logs",
				Columns:    []*schema.Column{NotificationLogsColumns[4]},
				RefColumns: []*schema.Column{EventsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notificationlog_channel_date_key",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[1], NotificationLogsColumns[3]},
			},
		},
	}
	// OneTimeNotificationsColumns holds the columns for the "one_time_notifications" table.
	OneTimeNotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "message", Type: field.TypeString, Size: 2147483647},
		{Name: "scheduled_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "sent_at", Type: field.TypeTime, Nullable: true},
	}
	// OneTimeNotificationsTable holds the schema information for the "one_time_notifications" table.
	OneTimeNotificationsTable = &schema.Table{
		Name:       "one_time_notifications",
		Columns:    OneTimeNotificationsColumns,
		PrimaryKey: []*schema.Column{OneTimeNotificationsColumns[0]},
	}
	// RecurringRulesColumns holds the columns for the "recurring_rules" table.
	RecurringRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "pattern_type", Type: field.TypeString},
		{Name: "nth", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "weekday", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "month", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "day", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RecurringRulesTable holds the schema information for the "recurring_rules" table.
	RecurringRulesTable = &schema.Table{
		Name:       "recurring_rules",
		Columns:    RecurringRulesColumns,
		PrimaryKey: []*schema.Column{RecurringRulesColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContactsTable,
		EventsTable,
		NotificationLogsTable,
		OneTimeNotificationsTable,
		RecurringRulesTable,
		SessionsTable,
		UsersTable,
	}
)

func init() {
	EventsTable.ForeignKeys[0].RefTable = ContactsTable
	NotificationLogsTable.ForeignKeys[0].RefTable = EventsTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
}
