// Code generated by ent, DO NOT EDIT.

package notificationdelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datey/datey/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldID, id))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannel, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldStatus, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldSentAt, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldErrorMessage, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldChannel, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldStatus, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotNull(FieldSentAt))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldErrorMessage, v))
}

// HasNotification applies the HasEdge predicate on the "notification" edge.
func HasNotification() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NotificationTable, NotificationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationWith applies the HasEdge predicate on the "notification" edge with a given conditions (other predicates).
func HasNotificationWith(preds ...predicate.OneTimeNotification) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(func(s *sql.Selector) {
		step := newNotificationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationDelivery) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationDelivery) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationDelivery) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.NotPredicates(p))
}
