// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datey/datey/ent/group"
	"github.com/datey/datey/ent/groupnote"
)

// GroupNoteCreate is the builder for creating a GroupNote entity.
type GroupNoteCreate struct {
	config
	mutation *GroupNoteMutation
	hooks    []Hook
}

// SetNote sets the "note" field.
func (_c *GroupNoteCreate) SetNote(v string) *GroupNoteCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNoteDate sets the "note_date" field.
func (_c *GroupNoteCreate) SetNoteDate(v time.Time) *GroupNoteCreate {
	_c.mutation.SetNoteDate(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupNoteCreate) SetCreatedAt(v time.Time) *GroupNoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupNoteCreate) SetUpdatedAt(v time.Time) *GroupNoteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_c *GroupNoteCreate) SetGroupID(id int) *GroupNoteCreate {
	_c.mutation.SetGroupID(id)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupNoteCreate) SetGroup(v *Group) *GroupNoteCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupNoteMutation object of the builder.
func (_c *GroupNoteCreate) Mutation() *GroupNoteMutation {
	return _c.mutation
}

// Save creates the GroupNote in the database.
func (_c *GroupNoteCreate) Save(ctx context.Context) (*GroupNote, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupNoteCreate) SaveX(ctx context.Context) *GroupNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupNoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupNoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupNoteCreate) check() error {
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "GroupNote.note"`)}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := groupnote.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "GroupNote.note": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NoteDate(); !ok {
		return &ValidationError{Name: "note_date", err: errors.New(`ent: missing required field "GroupNote.note_date"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupNote.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupNote.updated_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupNote.group"`)}
	}
	return nil
}

func (_c *GroupNoteCreate) sqlSave(ctx context.Context) (*GroupNote, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupNoteCreate) createSpec() (*GroupNote, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupNote{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupnote.Table, sqlgraph.NewFieldSpec(groupnote.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(groupnote.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.NoteDate(); ok {
		_spec.SetField(groupnote.FieldNoteDate, field.TypeTime, value)
		_node.NoteDate = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupnote.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupnote.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupnote.GroupTable,
			Columns: []string{groupnote.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_notes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupNoteCreateBulk is the builder for creating many GroupNote entities in bulk.
type GroupNoteCreateBulk struct {
	config
	err      error
	builders []*GroupNoteCreate
}

// Save creates the GroupNote entities in the database.
func (_c *GroupNoteCreateBulk) Save(ctx context.Context) ([]*GroupNote, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupNote, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupNoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupNoteCreateBulk) SaveX(ctx context.Context) []*GroupNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupNoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupNoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
