// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datey/datey/ent/group"
	"github.com/datey/datey/ent/groupnote"
	"github.com/datey/datey/ent/predicate"
)

// GroupNoteUpdate is the builder for updating GroupNote entities.
type GroupNoteUpdate struct {
	config
	hooks    []Hook
	mutation *GroupNoteMutation
}

// Where appends a list predicates to the GroupNoteUpdate builder.
func (_u *GroupNoteUpdate) Where(ps ...predicate.GroupNote) *GroupNoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNote sets the "note" field.
func (_u *GroupNoteUpdate) SetNote(v string) *GroupNoteUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *GroupNoteUpdate) SetNillableNote(v *string) *GroupNoteUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetNoteDate sets the "note_date" field.
func (_u *GroupNoteUpdate) SetNoteDate(v time.Time) *GroupNoteUpdate {
	_u.mutation.SetNoteDate(v)
	return _u
}

// SetNillableNoteDate sets the "note_date" field if the given value is not nil.
func (_u *GroupNoteUpdate) SetNillableNoteDate(v *time.Time) *GroupNoteUpdate {
	if v != nil {
		_u.SetNoteDate(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupNoteUpdate) SetCreatedAt(v time.Time) *GroupNoteUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupNoteUpdate) SetNillableCreatedAt(v *time.Time) *GroupNoteUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupNoteUpdate) SetUpdatedAt(v time.Time) *GroupNoteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GroupNoteUpdate) SetNillableUpdatedAt(v *time.Time) *GroupNoteUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *GroupNoteUpdate) SetGroupID(id int) *GroupNoteUpdate {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupNoteUpdate) SetGroup(v *Group) *GroupNoteUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupNoteMutation object of the builder.
func (_u *GroupNoteUpdate) Mutation() *GroupNoteMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupNoteUpdate) ClearGroup() *GroupNoteUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupNoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupNoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupNoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupNoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupNoteUpdate) check() error {
	if v, ok := _u.mutation.Note(); ok {
		if err := groupnote.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "GroupNote.note": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupNote.group"`)
	}
	return nil
}

func (_u *GroupNoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupnote.Table, groupnote.Columns, sqlgraph.NewFieldSpec(groupnote.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(groupnote.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.NoteDate(); ok {
		_spec.SetField(groupnote.FieldNoteDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupnote.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupnote.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupnote.GroupTable,
			Columns: []string{groupnote.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupnote.GroupTable,
			Columns: []string{groupnote.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupNoteUpdateOne is the builder for updating a single GroupNote entity.
type GroupNoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupNoteMutation
}

// SetNote sets the "note" field.
func (_u *GroupNoteUpdateOne) SetNote(v string) *GroupNoteUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *GroupNoteUpdateOne) SetNillableNote(v *string) *GroupNoteUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetNoteDate sets the "note_date" field.
func (_u *GroupNoteUpdateOne) SetNoteDate(v time.Time) *GroupNoteUpdateOne {
	_u.mutation.SetNoteDate(v)
	return _u
}

// SetNillableNoteDate sets the "note_date" field if the given value is not nil.
func (_u *GroupNoteUpdateOne) SetNillableNoteDate(v *time.Time) *GroupNoteUpdateOne {
	if v != nil {
		_u.SetNoteDate(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupNoteUpdateOne) SetCreatedAt(v time.Time) *GroupNoteUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupNoteUpdateOne) SetNillableCreatedAt(v *time.Time) *GroupNoteUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupNoteUpdateOne) SetUpdatedAt(v time.Time) *GroupNoteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GroupNoteUpdateOne) SetNillableUpdatedAt(v *time.Time) *GroupNoteUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *GroupNoteUpdateOne) SetGroupID(id int) *GroupNoteUpdateOne {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupNoteUpdateOne) SetGroup(v *Group) *GroupNoteUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupNoteMutation object of the builder.
func (_u *GroupNoteUpdateOne) Mutation() *GroupNoteMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupNoteUpdateOne) ClearGroup() *GroupNoteUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the GroupNoteUpdate builder.
func (_u *GroupNoteUpdateOne) Where(ps ...predicate.GroupNote) *GroupNoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupNoteUpdateOne) Select(field string, fields ...string) *GroupNoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupNote entity.
func (_u *GroupNoteUpdateOne) Save(ctx context.Context) (*GroupNote, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupNoteUpdateOne) SaveX(ctx context.Context) *GroupNote {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupNoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupNoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupNoteUpdateOne) check() error {
	if v, ok := _u.mutation.Note(); ok {
		if err := groupnote.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "GroupNote.note": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupNote.group"`)
	}
	return nil
}

func (_u *GroupNoteUpdateOne) sqlSave(ctx context.Context) (_node *GroupNote, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupnote.Table, groupnote.Columns, sqlgraph.NewFieldSpec(groupnote.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupNote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupnote.FieldID)
		for _, f := range fields {
			if !groupnote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupnote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(groupnote.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.NoteDate(); ok {
		_spec.SetField(groupnote.FieldNoteDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupnote.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupnote.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupnote.GroupTable,
			Columns: []string{groupnote.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupnote.GroupTable,
			Columns: []string{groupnote.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupNote{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
