// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datey/datey/ent/migrationlog"
)

// MigrationLog is the model entity for the MigrationLog schema.
type MigrationLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AppliedAt holds the value of the "applied_at" field.
	AppliedAt    time.Time `json:"applied_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MigrationLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case migrationlog.FieldID:
			values[i] = new(sql.NullInt64)
		case migrationlog.FieldName:
			values[i] = new(sql.NullString)
		case migrationlog.FieldAppliedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MigrationLog fields.
func (_m *MigrationLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case migrationlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case migrationlog.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case migrationlog.FieldAppliedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field applied_at", values[i])
			} else if value.Valid {
				_m.AppliedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MigrationLog.
// This includes values selected through modifiers, order, etc.
func (_m *MigrationLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MigrationLog.
// Note that you need to call MigrationLog.Unwrap() before calling this method if this MigrationLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MigrationLog) Update() *MigrationLogUpdateOne {
	return NewMigrationLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MigrationLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MigrationLog) Unwrap() *MigrationLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MigrationLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MigrationLog) String() string {
	var builder strings.Builder
	builder.WriteString("MigrationLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("applied_at=")
	builder.WriteString(_m.AppliedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MigrationLogs is a parsable slice of MigrationLog.
type MigrationLogs []*MigrationLog
