// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datey/datey/ent/event"
	"github.com/datey/datey/ent/notificationlog"
)

// NotificationLog is the model entity for the NotificationLog schema.
type NotificationLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt time.Time `json:"sent_at,omitempty"`
	// DateKey holds the value of the "date_key" field.
	DateKey string `json:"date_key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationLogQuery when eager-loading is set.
	Edges                   NotificationLogEdges `json:"edges"`
	event_notification_logs *int
	selectValues            sql.SelectValues
}

// NotificationLogEdges holds the relations/edges for other nodes in the graph.
type NotificationLogEdges struct {
	// Event holds the value of the event edge.
	Event *Event `json:"event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationLogEdges) EventOrErr() (*Event, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: event.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationlog.FieldID:
			values[i] = new(sql.NullInt64)
		case notificationlog.FieldChannel, notificationlog.FieldDateKey:
			values[i] = new(sql.NullString)
		case notificationlog.FieldSentAt:
			values[i] = new(sql.NullTime)
		case notificationlog.ForeignKeys[0]: // event_notification_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationLog fields.
func (_m *NotificationLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case notificationlog.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case notificationlog.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = value.Time
			}
		case notificationlog.FieldDateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date_key", values[i])
			} else if value.Valid {
				_m.DateKey = value.String
			}
		case notificationlog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field event_notification_logs", value)
			} else if value.Valid {
				_m.event_notification_logs = new(int)
				*_m.event_notification_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationLog.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the NotificationLog entity.
func (_m *NotificationLog) QueryEvent() *EventQuery {
	return NewNotificationLogClient(_m.config).QueryEvent(_m)
}

// Update returns a builder for updating this NotificationLog.
// Note that you need to call NotificationLog.Unwrap() before calling this method if this NotificationLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationLog) Update() *NotificationLogUpdateOne {
	return NewNotificationLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationLog) Unwrap() *NotificationLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationLog) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	builder.WriteString("sent_at=")
	builder.WriteString(_m.SentAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date_key=")
	builder.WriteString(_m.DateKey)
	builder.WriteByte(')')
	return builder.String()
}

// NotificationLogs is a parsable slice of NotificationLog.
type NotificationLogs []*NotificationLog
