// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datey/datey/ent/event"
	"github.com/datey/datey/ent/notificationlog"
	"github.com/datey/datey/ent/predicate"
)

// NotificationLogUpdate is the builder for updating NotificationLog entities.
type NotificationLogUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationLogMutation
}

// Where appends a list predicates to the NotificationLogUpdate builder.
func (_u *NotificationLogUpdate) Where(ps ...predicate.NotificationLog) *NotificationLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannel sets the "channel" field.
func (_u *NotificationLogUpdate) SetChannel(v string) *NotificationLogUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableChannel(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *NotificationLogUpdate) SetSentAt(v time.Time) *NotificationLogUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableSentAt(v *time.Time) *NotificationLogUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// SetDateKey sets the "date_key" field.
func (_u *NotificationLogUpdate) SetDateKey(v string) *NotificationLogUpdate {
	_u.mutation.SetDateKey(v)
	return _u
}

// SetNillableDateKey sets the "date_key" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableDateKey(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetDateKey(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *NotificationLogUpdate) SetEventID(id int) *NotificationLogUpdate {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *NotificationLogUpdate) SetEvent(v *Event) *NotificationLogUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the NotificationLogMutation object of the builder.
func (_u *NotificationLogUpdate) Mutation() *NotificationLogMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *NotificationLogUpdate) ClearEvent() *NotificationLogUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationLogUpdate) check() error {
	if v, ok := _u.mutation.Channel(); ok {
		if err := notificationlog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DateKey(); ok {
		if err := notificationlog.DateKeyValidator(v); err != nil {
			return &ValidationError{Name: "date_key", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.date_key": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationLog.event"`)
	}
	return nil
}

func (_u *NotificationLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationlog.Table, notificationlog.Columns, sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(notificationlog.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(notificationlog.FieldSentAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateKey(); ok {
		_spec.SetField(notificationlog.FieldDateKey, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationlog.EventTable,
			Columns: []string{notificationlog.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationlog.EventTable,
			Columns: []string{notificationlog.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationLogUpdateOne is the builder for updating a single NotificationLog entity.
type NotificationLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationLogMutation
}

// SetChannel sets the "channel" field.
func (_u *NotificationLogUpdateOne) SetChannel(v string) *NotificationLogUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableChannel(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *NotificationLogUpdateOne) SetSentAt(v time.Time) *NotificationLogUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableSentAt(v *time.Time) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// SetDateKey sets the "date_key" field.
func (_u *NotificationLogUpdateOne) SetDateKey(v string) *NotificationLogUpdateOne {
	_u.mutation.SetDateKey(v)
	return _u
}

// SetNillableDateKey sets the "date_key" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableDateKey(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetDateKey(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *NotificationLogUpdateOne) SetEventID(id int) *NotificationLogUpdateOne {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *NotificationLogUpdateOne) SetEvent(v *Event) *NotificationLogUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the NotificationLogMutation object of the builder.
func (_u *NotificationLogUpdateOne) Mutation() *NotificationLogMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *NotificationLogUpdateOne) ClearEvent() *NotificationLogUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the NotificationLogUpdate builder.
func (_u *NotificationLogUpdateOne) Where(ps ...predicate.NotificationLog) *NotificationLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationLogUpdateOne) Select(field string, fields ...string) *NotificationLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationLog entity.
func (_u *NotificationLogUpdateOne) Save(ctx context.Context) (*NotificationLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationLogUpdateOne) SaveX(ctx context.Context) *NotificationLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationLogUpdateOne) check() error {
	if v, ok := _u.mutation.Channel(); ok {
		if err := notificationlog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DateKey(); ok {
		if err := notificationlog.DateKeyValidator(v); err != nil {
			return &ValidationError{Name: "date_key", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.date_key": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationLog.event"`)
	}
	return nil
}

func (_u *NotificationLogUpdateOne) sqlSave(ctx context.Context) (_node *NotificationLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationlog.Table, notificationlog.Columns, sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationlog.FieldID)
		for _, f := range fields {
			if !notificationlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(notificationlog.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(notificationlog.FieldSentAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateKey(); ok {
		_spec.SetField(notificationlog.FieldDateKey, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationlog.EventTable,
			Columns: []string{notificationlog.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationlog.EventTable,
			Columns: []string{notificationlog.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
