// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datey/datey/ent/notificationdelivery"
	"github.com/datey/datey/ent/onetimenotification"
)

// NotificationDelivery is the model entity for the NotificationDelivery schema.
type NotificationDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt *time.Time `json:"sent_at,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationDeliveryQuery when eager-loading is set.
	Edges                            NotificationDeliveryEdges `json:"edges"`
	one_time_notification_deliveries *int
	selectValues                     sql.SelectValues
}

// NotificationDeliveryEdges holds the relations/edges for other nodes in the graph.
type NotificationDeliveryEdges struct {
	// Notification holds the value of the notification edge.
	Notification *OneTimeNotification `json:"notification,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NotificationOrErr returns the Notification value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationDeliveryEdges) NotificationOrErr() (*OneTimeNotification, error) {
	if e.Notification != nil {
		return e.Notification, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: onetimenotification.Label}
	}
	return nil, &NotLoadedError{edge: "notification"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationdelivery.FieldID:
			values[i] = new(sql.NullInt64)
		case notificationdelivery.FieldChannel, notificationdelivery.FieldStatus, notificationdelivery.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case notificationdelivery.FieldSentAt:
			values[i] = new(sql.NullTime)
		case notificationdelivery.ForeignKeys[0]: // one_time_notification_deliveries
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationDelivery fields.
func (_m *NotificationDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationdelivery.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case notificationdelivery.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case notificationdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case notificationdelivery.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = new(time.Time)
				*_m.SentAt = value.Time
			}
		case notificationdelivery.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case notificationdelivery.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field one_time_notification_deliveries", value)
			} else if value.Valid {
				_m.one_time_notification_deliveries = new(int)
				*_m.one_time_notification_deliveries = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNotification queries the "notification" edge of the NotificationDelivery entity.
func (_m *NotificationDelivery) QueryNotification() *OneTimeNotificationQuery {
	return NewNotificationDeliveryClient(_m.config).QueryNotification(_m)
}

// Update returns a builder for updating this NotificationDelivery.
// Note that you need to call NotificationDelivery.Unwrap() before calling this method if this NotificationDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationDelivery) Update() *NotificationDeliveryUpdateOne {
	return NewNotificationDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationDelivery) Unwrap() *NotificationDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SentAt; v != nil {
		builder.WriteString("sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteByte(')')
	return builder.String()
}

// NotificationDeliveries is a parsable slice of NotificationDelivery.
type NotificationDeliveries []*NotificationDelivery
