// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datey/datey/ent/notificationdelivery"
	"github.com/datey/datey/ent/onetimenotification"
)

// OneTimeNotificationCreate is the builder for creating a OneTimeNotification entity.
type OneTimeNotificationCreate struct {
	config
	mutation *OneTimeNotificationMutation
	hooks    []Hook
}

// SetMessage sets the "message" field.
func (_c *OneTimeNotificationCreate) SetMessage(v string) *OneTimeNotificationCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetScheduledAt sets the "scheduled_at" field.
func (_c *OneTimeNotificationCreate) SetScheduledAt(v time.Time) *OneTimeNotificationCreate {
	_c.mutation.SetScheduledAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OneTimeNotificationCreate) SetStatus(v string) *OneTimeNotificationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OneTimeNotificationCreate) SetNillableStatus(v *string) *OneTimeNotificationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OneTimeNotificationCreate) SetCreatedAt(v time.Time) *OneTimeNotificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *OneTimeNotificationCreate) SetSentAt(v time.Time) *OneTimeNotificationCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *OneTimeNotificationCreate) SetNillableSentAt(v *time.Time) *OneTimeNotificationCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetChannelTargets sets the "channel_targets" field.
func (_c *OneTimeNotificationCreate) SetChannelTargets(v string) *OneTimeNotificationCreate {
	_c.mutation.SetChannelTargets(v)
	return _c
}

// SetNillableChannelTargets sets the "channel_targets" field if the given value is not nil.
func (_c *OneTimeNotificationCreate) SetNillableChannelTargets(v *string) *OneTimeNotificationCreate {
	if v != nil {
		_c.SetChannelTargets(*v)
	}
	return _c
}

// SetPersonID sets the "person_id" field.
func (_c *OneTimeNotificationCreate) SetPersonID(v int) *OneTimeNotificationCreate {
	_c.mutation.SetPersonID(v)
	return _c
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_c *OneTimeNotificationCreate) SetNillablePersonID(v *int) *OneTimeNotificationCreate {
	if v != nil {
		_c.SetPersonID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *OneTimeNotificationCreate) SetEventType(v string) *OneTimeNotificationCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *OneTimeNotificationCreate) SetNillableEventType(v *string) *OneTimeNotificationCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// AddDeliveryIDs adds the "deliveries" edge to the NotificationDelivery entity by IDs.
func (_c *OneTimeNotificationCreate) AddDeliveryIDs(ids ...int) *OneTimeNotificationCreate {
	_c.mutation.AddDeliveryIDs(ids...)
	return _c
}

// AddDeliveries adds the "deliveries" edges to the NotificationDelivery entity.
func (_c *OneTimeNotificationCreate) AddDeliveries(v ...*NotificationDelivery) *OneTimeNotificationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeliveryIDs(ids...)
}

// Mutation returns the OneTimeNotificationMutation object of the builder.
func (_c *OneTimeNotificationCreate) Mutation() *OneTimeNotificationMutation {
	return _c.mutation
}

// Save creates the OneTimeNotification in the database.
func (_c *OneTimeNotificationCreate) Save(ctx context.Context) (*OneTimeNotification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OneTimeNotificationCreate) SaveX(ctx context.Context) *OneTimeNotification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OneTimeNotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OneTimeNotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OneTimeNotificationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := onetimenotification.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ChannelTargets(); !ok {
		v := onetimenotification.DefaultChannelTargets
		_c.mutation.SetChannelTargets(v)
	}
	if _, ok := _c.mutation.EventType(); !ok {
		v := onetimenotification.DefaultEventType
		_c.mutation.SetEventType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OneTimeNotificationCreate) check() error {
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "OneTimeNotification.message"`)}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := onetimenotification.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "OneTimeNotification.message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScheduledAt(); !ok {
		return &ValidationError{Name: "scheduled_at", err: errors.New(`ent: missing required field "OneTimeNotification.scheduled_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OneTimeNotification.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OneTimeNotification.created_at"`)}
	}
	return nil
}

func (_c *OneTimeNotificationCreate) sqlSave(ctx context.Context) (*OneTimeNotification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OneTimeNotificationCreate) createSpec() (*OneTimeNotification, *sqlgraph.CreateSpec) {
	var (
		_node = &OneTimeNotification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(onetimenotification.Table, sqlgraph.NewFieldSpec(onetimenotification.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(onetimenotification.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.ScheduledAt(); ok {
		_spec.SetField(onetimenotification.FieldScheduledAt, field.TypeTime, value)
		_node.ScheduledAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(onetimenotification.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(onetimenotification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(onetimenotification.FieldSentAt, field.TypeTime, value)
		_node.SentAt = &value
	}
	if value, ok := _c.mutation.ChannelTargets(); ok {
		_spec.SetField(onetimenotification.FieldChannelTargets, field.TypeString, value)
		_node.ChannelTargets = value
	}
	if value, ok := _c.mutation.PersonID(); ok {
		_spec.SetField(onetimenotification.FieldPersonID, field.TypeInt, value)
		_node.PersonID = &value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(onetimenotification.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if nodes := _c.mutation.DeliveriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   onetimenotification.DeliveriesTable,
			Columns: []string{onetimenotification.DeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationdelivery.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OneTimeNotificationCreateBulk is the builder for creating many OneTimeNotification entities in bulk.
type OneTimeNotificationCreateBulk struct {
	config
	err      error
	builders []*OneTimeNotificationCreate
}

// Save creates the OneTimeNotification entities in the database.
func (_c *OneTimeNotificationCreateBulk) Save(ctx context.Context) ([]*OneTimeNotification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OneTimeNotification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OneTimeNotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OneTimeNotificationCreateBulk) SaveX(ctx context.Context) []*OneTimeNotification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OneTimeNotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OneTimeNotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
