// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datey/datey/ent/passwordresettoken"
	"github.com/datey/datey/ent/user"
)

// PasswordResetToken is the model entity for the PasswordResetToken schema.
type PasswordResetToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Used holds the value of the "used" field.
	Used bool `json:"used,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PasswordResetTokenQuery when eager-loading is set.
	Edges                      PasswordResetTokenEdges `json:"edges"`
	user_password_reset_tokens *int
	selectValues               sql.SelectValues
}

// PasswordResetTokenEdges holds the relations/edges for other nodes in the graph.
type PasswordResetTokenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PasswordResetTokenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PasswordResetToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passwordresettoken.FieldUsed:
			values[i] = new(sql.NullBool)
		case passwordresettoken.FieldID:
			values[i] = new(sql.NullInt64)
		case passwordresettoken.FieldTokenHash:
			values[i] = new(sql.NullString)
		case passwordresettoken.FieldExpiresAt, passwordresettoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case passwordresettoken.ForeignKeys[0]: // user_password_reset_tokens
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PasswordResetToken fields.
func (_m *PasswordResetToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passwordresettoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case passwordresettoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case passwordresettoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case passwordresettoken.FieldUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field used", values[i])
			} else if value.Valid {
				_m.Used = value.Bool
			}
		case passwordresettoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case passwordresettoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_password_reset_tokens", value)
			} else if value.Valid {
				_m.user_password_reset_tokens = new(int)
				*_m.user_password_reset_tokens = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PasswordResetToken.
// This includes values selected through modifiers, order, etc.
func (_m *PasswordResetToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PasswordResetToken entity.
func (_m *PasswordResetToken) QueryUser() *UserQuery {
	return NewPasswordResetTokenClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PasswordResetToken.
// Note that you need to call PasswordResetToken.Unwrap() before calling this method if this PasswordResetToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PasswordResetToken) Update() *PasswordResetTokenUpdateOne {
	return NewPasswordResetTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PasswordResetToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PasswordResetToken) Unwrap() *PasswordResetToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PasswordResetToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PasswordResetToken) String() string {
	var builder strings.Builder
	builder.WriteString("PasswordResetToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("used=")
	builder.WriteString(fmt.Sprintf("%v", _m.Used))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PasswordResetTokens is a parsable slice of PasswordResetToken.
type PasswordResetTokens []*PasswordResetToken
