// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datey/datey/ent/person"
	"github.com/datey/datey/ent/relationship"
)

// RelationshipCreate is the builder for creating a Relationship entity.
type RelationshipCreate struct {
	config
	mutation *RelationshipMutation
	hooks    []Hook
}

// SetFromID sets the "from_id" field.
func (_c *RelationshipCreate) SetFromID(v int) *RelationshipCreate {
	_c.mutation.SetFromID(v)
	return _c
}

// SetToID sets the "to_id" field.
func (_c *RelationshipCreate) SetToID(v int) *RelationshipCreate {
	_c.mutation.SetToID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *RelationshipCreate) SetType(v relationship.Type) *RelationshipCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *RelationshipCreate) SetLabel(v string) *RelationshipCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *RelationshipCreate) SetNillableLabel(v *string) *RelationshipCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetFromPersonID sets the "from_person" edge to the Person entity by ID.
func (_c *RelationshipCreate) SetFromPersonID(id int) *RelationshipCreate {
	_c.mutation.SetFromPersonID(id)
	return _c
}

// SetFromPerson sets the "from_person" edge to the Person entity.
func (_c *RelationshipCreate) SetFromPerson(v *Person) *RelationshipCreate {
	return _c.SetFromPersonID(v.ID)
}

// SetToPersonID sets the "to_person" edge to the Person entity by ID.
func (_c *RelationshipCreate) SetToPersonID(id int) *RelationshipCreate {
	_c.mutation.SetToPersonID(id)
	return _c
}

// SetToPerson sets the "to_person" edge to the Person entity.
func (_c *RelationshipCreate) SetToPerson(v *Person) *RelationshipCreate {
	return _c.SetToPersonID(v.ID)
}

// Mutation returns the RelationshipMutation object of the builder.
func (_c *RelationshipCreate) Mutation() *RelationshipMutation {
	return _c.mutation
}

// Save creates the Relationship in the database.
func (_c *RelationshipCreate) Save(ctx context.Context) (*Relationship, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelationshipCreate) SaveX(ctx context.Context) *Relationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelationshipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelationshipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelationshipCreate) check() error {
	if _, ok := _c.mutation.FromID(); !ok {
		return &ValidationError{Name: "from_id", err: errors.New(`ent: missing required field "Relationship.from_id"`)}
	}
	if _, ok := _c.mutation.ToID(); !ok {
		return &ValidationError{Name: "to_id", err: errors.New(`ent: missing required field "Relationship.to_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Relationship.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := relationship.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Relationship.type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := relationship.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Relationship.label": %w`, err)}
		}
	}
	if len(_c.mutation.FromPersonIDs()) == 0 {
		return &ValidationError{Name: "from_person", err: errors.New(`ent: missing required edge "Relationship.from_person"`)}
	}
	if len(_c.mutation.ToPersonIDs()) == 0 {
		return &ValidationError{Name: "to_person", err: errors.New(`ent: missing required edge "Relationship.to_person"`)}
	}
	return nil
}

func (_c *RelationshipCreate) sqlSave(ctx context.Context) (*Relationship, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelationshipCreate) createSpec() (*Relationship, *sqlgraph.CreateSpec) {
	var (
		_node = &Relationship{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relationship.Table, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(relationship.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(relationship.FieldLabel, field.TypeString, value)
		_node.Label = &value
	}
	if nodes := _c.mutation.FromPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.FromPersonTable,
			Columns: []string{relationship.FromPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FromID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ToPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.ToPersonTable,
			Columns: []string{relationship.ToPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ToID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RelationshipCreateBulk is the builder for creating many Relationship entities in bulk.
type RelationshipCreateBulk struct {
	config
	err      error
	builders []*RelationshipCreate
}

// Save creates the Relationship entities in the database.
func (_c *RelationshipCreateBulk) Save(ctx context.Context) ([]*Relationship, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Relationship, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelationshipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelationshipCreateBulk) SaveX(ctx context.Context) []*Relationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelationshipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelationshipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
