// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/datey/datey/ent/contact"
	"github.com/datey/datey/ent/event"
	"github.com/datey/datey/ent/notificationlog"
	"github.com/datey/datey/ent/onetimenotification"
	"github.com/datey/datey/ent/recurringrule"
	"github.com/datey/datey/ent/schema"
	"github.com/datey/datey/ent/session"
	"github.com/datey/datey/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescName is the schema descriptor for name field.
	contactDescName := contactFields[0].Descriptor()
	// contact.NameValidator is a validator for the "name" field. It is called by the builders before save.
	contact.NameValidator = contactDescName.Validators[0].(func(string) error)
	// contactDescNotes is the schema descriptor for notes field.
	contactDescNotes := contactFields[1].Descriptor()
	// contact.DefaultNotes holds the default value on creation for the notes field.
	contact.DefaultNotes = contactDescNotes.Default.(string)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescType is the schema descriptor for type field.
	eventDescType := eventFields[0].Descriptor()
	// event.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	event.TypeValidator = eventDescType.Validators[0].(func(string) error)
	// eventDescDescription is the schema descriptor for description field.
	eventDescDescription := eventFields[2].Descriptor()
	// event.DefaultDescription holds the default value on creation for the description field.
	event.DefaultDescription = eventDescDescription.Default.(string)
	notificationlogFields := schema.NotificationLog{}.Fields()
	_ = notificationlogFields
	// notificationlogDescChannel is the schema descriptor for channel field.
	notificationlogDescChannel := notificationlogFields[0].Descriptor()
	// notificationlog.ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	notificationlog.ChannelValidator = notificationlogDescChannel.Validators[0].(func(string) error)
	// notificationlogDescDateKey is the schema descriptor for date_key field.
	notificationlogDescDateKey := notificationlogFields[2].Descriptor()
	// notificationlog.DateKeyValidator is a validator for the "date_key" field. It is called by the builders before save.
	notificationlog.DateKeyValidator = notificationlogDescDateKey.Validators[0].(func(string) error)
	onetimenotificationFields := schema.OneTimeNotification{}.Fields()
	_ = onetimenotificationFields
	// onetimenotificationDescMessage is the schema descriptor for message field.
	onetimenotificationDescMessage := onetimenotificationFields[0].Descriptor()
	// onetimenotification.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	onetimenotification.MessageValidator = onetimenotificationDescMessage.Validators[0].(func(string) error)
	// onetimenotificationDescStatus is the schema descriptor for status field.
	onetimenotificationDescStatus := onetimenotificationFields[2].Descriptor()
	// onetimenotification.DefaultStatus holds the default value on creation for the status field.
	onetimenotification.DefaultStatus = onetimenotificationDescStatus.Default.(string)
	recurringruleFields := schema.RecurringRule{}.Fields()
	_ = recurringruleFields
	// recurringruleDescName is the schema descriptor for name field.
	recurringruleDescName := recurringruleFields[0].Descriptor()
	// recurringrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	recurringrule.NameValidator = recurringruleDescName.Validators[0].(func(string) error)
	// recurringruleDescPatternType is the schema descriptor for pattern_type field.
	recurringruleDescPatternType := recurringruleFields[1].Descriptor()
	// recurringrule.PatternTypeValidator is a validator for the "pattern_type" field. It is called by the builders before save.
	recurringrule.PatternTypeValidator = recurringruleDescPatternType.Validators[0].(func(string) error)
	// recurringruleDescNth is the schema descriptor for nth field.
	recurringruleDescNth := recurringruleFields[2].Descriptor()
	// recurringrule.DefaultNth holds the default value on creation for the nth field.
	recurringrule.DefaultNth = recurringruleDescNth.Default.(int)
	// recurringruleDescWeekday is the schema descriptor for weekday field.
	recurringruleDescWeekday := recurringruleFields[3].Descriptor()
	// recurringrule.DefaultWeekday holds the default value on creation for the weekday field.
	recurringrule.DefaultWeekday = recurringruleDescWeekday.Default.(int)
	// recurringruleDescMonth is the schema descriptor for month field.
	recurringruleDescMonth := recurringruleFields[4].Descriptor()
	// recurringrule.DefaultMonth holds the default value on creation for the month field.
	recurringrule.DefaultMonth = recurringruleDescMonth.Default.(int)
	// recurringruleDescDay is the schema descriptor for day field.
	recurringruleDescDay := recurringruleFields[5].Descriptor()
	// recurringrule.DefaultDay holds the default value on creation for the day field.
	recurringrule.DefaultDay = recurringruleDescDay.Default.(int)
	// recurringruleDescEnabled is the schema descriptor for enabled field.
	recurringruleDescEnabled := recurringruleFields[6].Descriptor()
	// recurringrule.DefaultEnabled holds the default value on creation for the enabled field.
	recurringrule.DefaultEnabled = recurringruleDescEnabled.Default.(bool)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[0].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
}
