// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/datey/datey/ent/contact"
	"github.com/datey/datey/ent/event"
	"github.com/datey/datey/ent/group"
	"github.com/datey/datey/ent/migrationlog"
	"github.com/datey/datey/ent/notificationlog"
	"github.com/datey/datey/ent/person"
	"github.com/datey/datey/ent/personnote"
	"github.com/datey/datey/ent/pushsubscription"
	"github.com/datey/datey/ent/recurringrule"
	"github.com/datey/datey/ent/schema"
	"github.com/datey/datey/ent/session"
	"github.com/datey/datey/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescName is the schema descriptor for name field.
	contactDescName := contactFields[0].Descriptor()
	// contact.NameValidator is a validator for the "name" field. It is called by the builders before save.
	contact.NameValidator = contactDescName.Validators[0].(func(string) error)
	// contactDescNotes is the schema descriptor for notes field.
	contactDescNotes := contactFields[1].Descriptor()
	// contact.DefaultNotes holds the default value on creation for the notes field.
	contact.DefaultNotes = contactDescNotes.Default.(string)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescType is the schema descriptor for type field.
	eventDescType := eventFields[0].Descriptor()
	// event.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	event.TypeValidator = eventDescType.Validators[0].(func(string) error)
	// eventDescDescription is the schema descriptor for description field.
	eventDescDescription := eventFields[2].Descriptor()
	// event.DefaultDescription holds the default value on creation for the description field.
	event.DefaultDescription = eventDescDescription.Default.(string)
	// eventDescNotes is the schema descriptor for notes field.
	eventDescNotes := eventFields[3].Descriptor()
	// event.DefaultNotes holds the default value on creation for the notes field.
	event.DefaultNotes = eventDescNotes.Default.(string)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	// groupDescDescription is the schema descriptor for description field.
	groupDescDescription := groupFields[1].Descriptor()
	// group.DefaultDescription holds the default value on creation for the description field.
	group.DefaultDescription = groupDescDescription.Default.(string)
	migrationlogFields := schema.MigrationLog{}.Fields()
	_ = migrationlogFields
	// migrationlogDescName is the schema descriptor for name field.
	migrationlogDescName := migrationlogFields[0].Descriptor()
	// migrationlog.NameValidator is a validator for the "name" field. It is called by the builders before save.
	migrationlog.NameValidator = migrationlogDescName.Validators[0].(func(string) error)
	notificationlogFields := schema.NotificationLog{}.Fields()
	_ = notificationlogFields
	// notificationlogDescChannel is the schema descriptor for channel field.
	notificationlogDescChannel := notificationlogFields[0].Descriptor()
	// notificationlog.ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	notificationlog.ChannelValidator = notificationlogDescChannel.Validators[0].(func(string) error)
	// notificationlogDescDateKey is the schema descriptor for date_key field.
	notificationlogDescDateKey := notificationlogFields[2].Descriptor()
	// notificationlog.DateKeyValidator is a validator for the "date_key" field. It is called by the builders before save.
	notificationlog.DateKeyValidator = notificationlogDescDateKey.Validators[0].(func(string) error)
	personFields := schema.Person{}.Fields()
	_ = personFields
	// personDescName is the schema descriptor for name field.
	personDescName := personFields[0].Descriptor()
	// person.NameValidator is a validator for the "name" field. It is called by the builders before save.
	person.NameValidator = personDescName.Validators[0].(func(string) error)
	// personDescNotes is the schema descriptor for notes field.
	personDescNotes := personFields[1].Descriptor()
	// person.DefaultNotes holds the default value on creation for the notes field.
	person.DefaultNotes = personDescNotes.Default.(string)
	// personDescNotifyBirthdays is the schema descriptor for notify_birthdays field.
	personDescNotifyBirthdays := personFields[3].Descriptor()
	// person.DefaultNotifyBirthdays holds the default value on creation for the notify_birthdays field.
	person.DefaultNotifyBirthdays = personDescNotifyBirthdays.Default.(bool)
	// personDescTimezone is the schema descriptor for timezone field.
	personDescTimezone := personFields[4].Descriptor()
	// person.DefaultTimezone holds the default value on creation for the timezone field.
	person.DefaultTimezone = personDescTimezone.Default.(string)
	// personDescImmichPhotoDisabled is the schema descriptor for immich_photo_disabled field.
	personDescImmichPhotoDisabled := personFields[7].Descriptor()
	// person.DefaultImmichPhotoDisabled holds the default value on creation for the immich_photo_disabled field.
	person.DefaultImmichPhotoDisabled = personDescImmichPhotoDisabled.Default.(bool)
	personnoteFields := schema.PersonNote{}.Fields()
	_ = personnoteFields
	// personnoteDescNote is the schema descriptor for note field.
	personnoteDescNote := personnoteFields[0].Descriptor()
	// personnote.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	personnote.NoteValidator = personnoteDescNote.Validators[0].(func(string) error)
	pushsubscriptionFields := schema.PushSubscription{}.Fields()
	_ = pushsubscriptionFields
	// pushsubscriptionDescEndpoint is the schema descriptor for endpoint field.
	pushsubscriptionDescEndpoint := pushsubscriptionFields[0].Descriptor()
	// pushsubscription.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	pushsubscription.EndpointValidator = pushsubscriptionDescEndpoint.Validators[0].(func(string) error)
	// pushsubscriptionDescP256dh is the schema descriptor for p256dh field.
	pushsubscriptionDescP256dh := pushsubscriptionFields[1].Descriptor()
	// pushsubscription.P256dhValidator is a validator for the "p256dh" field. It is called by the builders before save.
	pushsubscription.P256dhValidator = pushsubscriptionDescP256dh.Validators[0].(func(string) error)
	// pushsubscriptionDescAuth is the schema descriptor for auth field.
	pushsubscriptionDescAuth := pushsubscriptionFields[2].Descriptor()
	// pushsubscription.AuthValidator is a validator for the "auth" field. It is called by the builders before save.
	pushsubscription.AuthValidator = pushsubscriptionDescAuth.Validators[0].(func(string) error)
	recurringruleFields := schema.RecurringRule{}.Fields()
	_ = recurringruleFields
	// recurringruleDescName is the schema descriptor for name field.
	recurringruleDescName := recurringruleFields[0].Descriptor()
	// recurringrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	recurringrule.NameValidator = recurringruleDescName.Validators[0].(func(string) error)
	// recurringruleDescPatternType is the schema descriptor for pattern_type field.
	recurringruleDescPatternType := recurringruleFields[1].Descriptor()
	// recurringrule.PatternTypeValidator is a validator for the "pattern_type" field. It is called by the builders before save.
	recurringrule.PatternTypeValidator = recurringruleDescPatternType.Validators[0].(func(string) error)
	// recurringruleDescNth is the schema descriptor for nth field.
	recurringruleDescNth := recurringruleFields[2].Descriptor()
	// recurringrule.DefaultNth holds the default value on creation for the nth field.
	recurringrule.DefaultNth = recurringruleDescNth.Default.(int)
	// recurringruleDescWeekday is the schema descriptor for weekday field.
	recurringruleDescWeekday := recurringruleFields[3].Descriptor()
	// recurringrule.DefaultWeekday holds the default value on creation for the weekday field.
	recurringrule.DefaultWeekday = recurringruleDescWeekday.Default.(int)
	// recurringruleDescMonth is the schema descriptor for month field.
	recurringruleDescMonth := recurringruleFields[4].Descriptor()
	// recurringrule.DefaultMonth holds the default value on creation for the month field.
	recurringrule.DefaultMonth = recurringruleDescMonth.Default.(int)
	// recurringruleDescDay is the schema descriptor for day field.
	recurringruleDescDay := recurringruleFields[5].Descriptor()
	// recurringrule.DefaultDay holds the default value on creation for the day field.
	recurringrule.DefaultDay = recurringruleDescDay.Default.(int)
	// recurringruleDescEnabled is the schema descriptor for enabled field.
	recurringruleDescEnabled := recurringruleFields[6].Descriptor()
	// recurringrule.DefaultEnabled holds the default value on creation for the enabled field.
	recurringrule.DefaultEnabled = recurringruleDescEnabled.Default.(bool)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[0].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescEinkMode is the schema descriptor for eink_mode field.
	userDescEinkMode := userFields[3].Descriptor()
	// user.DefaultEinkMode holds the default value on creation for the eink_mode field.
	user.DefaultEinkMode = userDescEinkMode.Default.(bool)
}
