// Code generated by ent, DO NOT EDIT.

package notificationlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datey/datey/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldID, id))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldChannel, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldSentAt, v))
}

// DateKey applies equality check predicate on the "date_key" field. It's identical to DateKeyEQ.
func DateKey(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldDateKey, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldChannel, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldSentAt, v))
}

// DateKeyEQ applies the EQ predicate on the "date_key" field.
func DateKeyEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldDateKey, v))
}

// DateKeyNEQ applies the NEQ predicate on the "date_key" field.
func DateKeyNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldDateKey, v))
}

// DateKeyIn applies the In predicate on the "date_key" field.
func DateKeyIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldDateKey, vs...))
}

// DateKeyNotIn applies the NotIn predicate on the "date_key" field.
func DateKeyNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldDateKey, vs...))
}

// DateKeyGT applies the GT predicate on the "date_key" field.
func DateKeyGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldDateKey, v))
}

// DateKeyGTE applies the GTE predicate on the "date_key" field.
func DateKeyGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldDateKey, v))
}

// DateKeyLT applies the LT predicate on the "date_key" field.
func DateKeyLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldDateKey, v))
}

// DateKeyLTE applies the LTE predicate on the "date_key" field.
func DateKeyLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldDateKey, v))
}

// DateKeyContains applies the Contains predicate on the "date_key" field.
func DateKeyContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldDateKey, v))
}

// DateKeyHasPrefix applies the HasPrefix predicate on the "date_key" field.
func DateKeyHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldDateKey, v))
}

// DateKeyHasSuffix applies the HasSuffix predicate on the "date_key" field.
func DateKeyHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldDateKey, v))
}

// DateKeyEqualFold applies the EqualFold predicate on the "date_key" field.
func DateKeyEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldDateKey, v))
}

// DateKeyContainsFold applies the ContainsFold predicate on the "date_key" field.
func DateKeyContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldDateKey, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.NotificationLog {
	return predicate.NotificationLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.NotificationLog {
	return predicate.NotificationLog(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationLog) predicate.NotificationLog {
	return predicate.NotificationLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationLog) predicate.NotificationLog {
	return predicate.NotificationLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationLog) predicate.NotificationLog {
	return predicate.NotificationLog(sql.NotPredicates(p))
}
