// Code generated by ent, DO NOT EDIT.

package groupnote

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datey/datey/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLTE(FieldID, id))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldNote, v))
}

// NoteDate applies equality check predicate on the "note_date" field. It's identical to NoteDateEQ.
func NoteDate(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldNoteDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldUpdatedAt, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldContainsFold(FieldNote, v))
}

// NoteDateEQ applies the EQ predicate on the "note_date" field.
func NoteDateEQ(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldNoteDate, v))
}

// NoteDateNEQ applies the NEQ predicate on the "note_date" field.
func NoteDateNEQ(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNEQ(FieldNoteDate, v))
}

// NoteDateIn applies the In predicate on the "note_date" field.
func NoteDateIn(vs ...time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldIn(FieldNoteDate, vs...))
}

// NoteDateNotIn applies the NotIn predicate on the "note_date" field.
func NoteDateNotIn(vs ...time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNotIn(FieldNoteDate, vs...))
}

// NoteDateGT applies the GT predicate on the "note_date" field.
func NoteDateGT(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGT(FieldNoteDate, v))
}

// NoteDateGTE applies the GTE predicate on the "note_date" field.
func NoteDateGTE(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGTE(FieldNoteDate, v))
}

// NoteDateLT applies the LT predicate on the "note_date" field.
func NoteDateLT(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLT(FieldNoteDate, v))
}

// NoteDateLTE applies the LTE predicate on the "note_date" field.
func NoteDateLTE(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLTE(FieldNoteDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupNote {
	return predicate.GroupNote(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupNote {
	return predicate.GroupNote(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupNote {
	return predicate.GroupNote(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupNote) predicate.GroupNote {
	return predicate.GroupNote(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupNote) predicate.GroupNote {
	return predicate.GroupNote(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupNote) predicate.GroupNote {
	return predicate.GroupNote(sql.NotPredicates(p))
}
