// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppConfig is the predicate function for appconfig builders.
type AppConfig func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// GiftIdea is the predicate function for giftidea builders.
type GiftIdea func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupNote is the predicate function for groupnote builders.
type GroupNote func(*sql.Selector)

// MigrationLog is the predicate function for migrationlog builders.
type MigrationLog func(*sql.Selector)

// NotificationLog is the predicate function for notificationlog builders.
type NotificationLog func(*sql.Selector)

// PasswordResetToken is the predicate function for passwordresettoken builders.
type PasswordResetToken func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// PersonNote is the predicate function for personnote builders.
type PersonNote func(*sql.Selector)

// PushSubscription is the predicate function for pushsubscription builders.
type PushSubscription func(*sql.Selector)

// RecurringRule is the predicate function for recurringrule builders.
type RecurringRule func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserNotificationChannel is the predicate function for usernotificationchannel builders.
type UserNotificationChannel func(*sql.Selector)
